{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "authorship_tag": "ABX9TyPjFWNt/7hU8Hy7MipN1iii"
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "code",
      "execution_count": 6,
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "rl_yGooqw198",
        "outputId": "db0d6be2-e430-4c20-bdd8-ffb8ee10791f"
      },
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "/content\n"
          ]
        }
      ],
      "source": [
        "import os\n",
        "%cd /content"
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "!pip install django"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "gMdb9klhxgSV",
        "outputId": "42c96384-98aa-4fba-8d04-c5386343ebb3"
      },
      "execution_count": 2,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Collecting django\n",
            "  Downloading Django-5.0.6-py3-none-any.whl (8.2 MB)\n",
            "\u001b[2K     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m8.2/8.2 MB\u001b[0m \u001b[31m42.1 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
            "\u001b[?25hCollecting asgiref<4,>=3.7.0 (from django)\n",
            "  Downloading asgiref-3.8.1-py3-none-any.whl (23 kB)\n",
            "Requirement already satisfied: sqlparse>=0.3.1 in /usr/local/lib/python3.10/dist-packages (from django) (0.5.0)\n",
            "Requirement already satisfied: typing-extensions>=4 in /usr/local/lib/python3.10/dist-packages (from asgiref<4,>=3.7.0->django) (4.12.2)\n",
            "Installing collected packages: asgiref, django\n",
            "Successfully installed asgiref-3.8.1 django-5.0.6\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "!django-admin startproject diary_project"
      ],
      "metadata": {
        "id": "ofLghMQuxh9c"
      },
      "execution_count": 3,
      "outputs": []
    },
    {
      "cell_type": "code",
      "source": [
        "%cd diary_project"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "dSwa4fuJxkTs",
        "outputId": "f1a787be-f400-40c9-a4fe-2413a7fbe26b"
      },
      "execution_count": 7,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "/content/diary_project\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "from google.colab.output import eval_js\n",
        "print(eval_js(\"google.colab.kernel.proxyPort(8000)\"))"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 35
        },
        "id": "_MOl6-ZexmWs",
        "outputId": "447ac9e1-dc87-406e-caa9-79a13f8826f4"
      },
      "execution_count": 5,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "https://wblc375m86-496ff2e9c6d22116-8000-colab.googleusercontent.com/\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "!python manage.py runserver 8000"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "zGif-g_wxn_V",
        "outputId": "c9294761-1eda-407e-a457-e6398be731fa"
      },
      "execution_count": null,
      "outputs": [
        {
          "metadata": {
            "tags": null
          },
          "name": "stdout",
          "output_type": "stream",
          "text": [
            "Watching for file changes with StatReloader\n",
            "Performing system checks...\n",
            "\n",
            "Exception in thread django-main-thread:\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/lib/python3.10/threading.py\", line 1016, in _bootstrap_inner\n",
            "    self.run()\n",
            "  File \"/usr/lib/python3.10/threading.py\", line 953, in run\n",
            "    self._target(*self._args, **self._kwargs)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/django/utils/autoreload.py\", line 64, in wrapper\n",
            "    fn(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/django/core/management/commands/runserver.py\", line 133, in inner_run\n",
            "    self.check(display_num_errors=True)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/django/core/management/base.py\", line 486, in check\n",
            "    all_issues = checks.run_checks(\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/django/core/checks/registry.py\", line 88, in run_checks\n",
            "    new_errors = check(app_configs=app_configs, databases=databases)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/django/core/checks/urls.py\", line 42, in check_url_namespaces_unique\n",
            "    all_namespaces = _load_all_namespaces(resolver)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/django/core/checks/urls.py\", line 61, in _load_all_namespaces\n",
            "    url_patterns = getattr(resolver, \"url_patterns\", [])\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/django/utils/functional.py\", line 47, in __get__\n",
            "    res = instance.__dict__[self.name] = self.func(instance)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/django/urls/resolvers.py\", line 738, in url_patterns\n",
            "    patterns = getattr(self.urlconf_module, \"urlpatterns\", self.urlconf_module)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/django/utils/functional.py\", line 47, in __get__\n",
            "    res = instance.__dict__[self.name] = self.func(instance)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/django/urls/resolvers.py\", line 731, in urlconf_module\n",
            "    return import_module(self.urlconf_name)\n",
            "  File \"/usr/lib/python3.10/importlib/__init__.py\", line 126, in import_module\n",
            "    return _bootstrap._gcd_import(name[level:], package, level)\n",
            "  File \"<frozen importlib._bootstrap>\", line 1050, in _gcd_import\n",
            "  File \"<frozen importlib._bootstrap>\", line 1027, in _find_and_load\n",
            "  File \"<frozen importlib._bootstrap>\", line 1006, in _find_and_load_unlocked\n",
            "  File \"<frozen importlib._bootstrap>\", line 688, in _load_unlocked\n",
            "  File \"<frozen importlib._bootstrap_external>\", line 883, in exec_module\n",
            "  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\n",
            "  File \"/content/diary_project/diary_project/urls.py\", line 22, in <module>\n",
            "    path('', include('diary.urls')),\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/django/urls/conf.py\", line 39, in include\n",
            "    urlconf_module = import_module(urlconf_module)\n",
            "  File \"/usr/lib/python3.10/importlib/__init__.py\", line 126, in import_module\n",
            "    return _bootstrap._gcd_import(name[level:], package, level)\n",
            "  File \"<frozen importlib._bootstrap>\", line 1050, in _gcd_import\n",
            "  File \"<frozen importlib._bootstrap>\", line 1027, in _find_and_load\n",
            "  File \"<frozen importlib._bootstrap>\", line 1006, in _find_and_load_unlocked\n",
            "  File \"<frozen importlib._bootstrap>\", line 688, in _load_unlocked\n",
            "  File \"<frozen importlib._bootstrap_external>\", line 883, in exec_module\n",
            "  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\n",
            "  File \"/content/diary_project/diary/urls.py\", line 3, in <module>\n",
            "    from .views import predict_view\n",
            "  File \"/content/diary_project/diary/views.py\", line 2, in <module>\n",
            "    from .depression_model import depression_predict\n",
            "  File \"/content/diary_project/diary/depression_model.py\", line 17\n",
            "    model1 = BERTClassifier(bertmodel,  dr_rate = 0.5).\n",
            "                                                       ^\n",
            "SyntaxError: invalid syntax\n",
            "/content/diary_project/diary/depression_model.py changed, reloading.\n",
            "Watching for file changes with StatReloader\n",
            "Performing system checks...\n",
            "\n",
            "Exception in thread django-main-thread:\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/lib/python3.10/threading.py\", line 1016, in _bootstrap_inner\n",
            "    self.run()\n",
            "  File \"/usr/lib/python3.10/threading.py\", line 953, in run\n",
            "    self._target(*self._args, **self._kwargs)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/django/utils/autoreload.py\", line 64, in wrapper\n",
            "    fn(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/django/core/management/commands/runserver.py\", line 133, in inner_run\n",
            "    self.check(display_num_errors=True)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/django/core/management/base.py\", line 486, in check\n",
            "    all_issues = checks.run_checks(\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/django/core/checks/registry.py\", line 88, in run_checks\n",
            "    new_errors = check(app_configs=app_configs, databases=databases)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/django/core/checks/urls.py\", line 42, in check_url_namespaces_unique\n",
            "    all_namespaces = _load_all_namespaces(resolver)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/django/core/checks/urls.py\", line 61, in _load_all_namespaces\n",
            "    url_patterns = getattr(resolver, \"url_patterns\", [])\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/django/utils/functional.py\", line 47, in __get__\n",
            "    res = instance.__dict__[self.name] = self.func(instance)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/django/urls/resolvers.py\", line 738, in url_patterns\n",
            "    patterns = getattr(self.urlconf_module, \"urlpatterns\", self.urlconf_module)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/django/utils/functional.py\", line 47, in __get__\n",
            "    res = instance.__dict__[self.name] = self.func(instance)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/django/urls/resolvers.py\", line 731, in urlconf_module\n",
            "    return import_module(self.urlconf_name)\n",
            "  File \"/usr/lib/python3.10/importlib/__init__.py\", line 126, in import_module\n",
            "    return _bootstrap._gcd_import(name[level:], package, level)\n",
            "  File \"<frozen importlib._bootstrap>\", line 1050, in _gcd_import\n",
            "  File \"<frozen importlib._bootstrap>\", line 1027, in _find_and_load\n",
            "  File \"<frozen importlib._bootstrap>\", line 1006, in _find_and_load_unlocked\n",
            "  File \"<frozen importlib._bootstrap>\", line 688, in _load_unlocked\n",
            "  File \"<frozen importlib._bootstrap_external>\", line 883, in exec_module\n",
            "  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\n",
            "  File \"/content/diary_project/diary_project/urls.py\", line 22, in <module>\n",
            "    path('', include('diary.urls')),\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/django/urls/conf.py\", line 39, in include\n",
            "    urlconf_module = import_module(urlconf_module)\n",
            "  File \"/usr/lib/python3.10/importlib/__init__.py\", line 126, in import_module\n",
            "    return _bootstrap._gcd_import(name[level:], package, level)\n",
            "  File \"<frozen importlib._bootstrap>\", line 1050, in _gcd_import\n",
            "  File \"<frozen importlib._bootstrap>\", line 1027, in _find_and_load\n",
            "  File \"<frozen importlib._bootstrap>\", line 1006, in _find_and_load_unlocked\n",
            "  File \"<frozen importlib._bootstrap>\", line 688, in _load_unlocked\n",
            "  File \"<frozen importlib._bootstrap_external>\", line 883, in exec_module\n",
            "  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\n",
            "  File \"/content/diary_project/diary/urls.py\", line 3, in <module>\n",
            "    from .views import predict_view\n",
            "  File \"/content/diary_project/diary/views.py\", line 2, in <module>\n",
            "    from .depression_model import depression_predict\n",
            "  File \"/content/diary_project/diary/depression_model.py\", line 17\n",
            "    model1 = BERTClassifier(bertmodel,  dr_rate = 0.5).\n",
            "                                                       ^\n",
            "SyntaxError: invalid syntax\n",
            "/content/diary_project/diary/depression_model.py changed, reloading.\n",
            "Watching for file changes with StatReloader\n",
            "Performing system checks...\n",
            "\n",
            "The tokenizer class you load from this checkpoint is not the same type as the class this function is called from. It may result in unexpected tokenization. \n",
            "The tokenizer class you load from this checkpoint is 'XLNetTokenizer'. \n",
            "The class this function is called from is 'KoBERTTokenizer'.\n",
            "The tokenizer class you load from this checkpoint is not the same type as the class this function is called from. It may result in unexpected tokenization. \n",
            "The tokenizer class you load from this checkpoint is 'XLNetTokenizer'. \n",
            "The class this function is called from is 'KoBERTTokenizer'.\n",
            "Exception in thread django-main-thread:\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/lib/python3.10/threading.py\", line 1016, in _bootstrap_inner\n",
            "    self.run()\n",
            "  File \"/usr/lib/python3.10/threading.py\", line 953, in run\n",
            "    self._target(*self._args, **self._kwargs)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/django/utils/autoreload.py\", line 64, in wrapper\n",
            "    fn(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/django/core/management/commands/runserver.py\", line 133, in inner_run\n",
            "    self.check(display_num_errors=True)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/django/core/management/base.py\", line 486, in check\n",
            "    all_issues = checks.run_checks(\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/django/core/checks/registry.py\", line 88, in run_checks\n",
            "    new_errors = check(app_configs=app_configs, databases=databases)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/django/core/checks/urls.py\", line 42, in check_url_namespaces_unique\n",
            "    all_namespaces = _load_all_namespaces(resolver)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/django/core/checks/urls.py\", line 61, in _load_all_namespaces\n",
            "    url_patterns = getattr(resolver, \"url_patterns\", [])\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/django/utils/functional.py\", line 47, in __get__\n",
            "    res = instance.__dict__[self.name] = self.func(instance)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/django/urls/resolvers.py\", line 738, in url_patterns\n",
            "    patterns = getattr(self.urlconf_module, \"urlpatterns\", self.urlconf_module)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/django/utils/functional.py\", line 47, in __get__\n",
            "    res = instance.__dict__[self.name] = self.func(instance)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/django/urls/resolvers.py\", line 731, in urlconf_module\n",
            "    return import_module(self.urlconf_name)\n",
            "  File \"/usr/lib/python3.10/importlib/__init__.py\", line 126, in import_module\n",
            "    return _bootstrap._gcd_import(name[level:], package, level)\n",
            "  File \"<frozen importlib._bootstrap>\", line 1050, in _gcd_import\n",
            "  File \"<frozen importlib._bootstrap>\", line 1027, in _find_and_load\n",
            "  File \"<frozen importlib._bootstrap>\", line 1006, in _find_and_load_unlocked\n",
            "  File \"<frozen importlib._bootstrap>\", line 688, in _load_unlocked\n",
            "  File \"<frozen importlib._bootstrap_external>\", line 883, in exec_module\n",
            "  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\n",
            "  File \"/content/diary_project/diary_project/urls.py\", line 22, in <module>\n",
            "    path('', include('diary.urls')),\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/django/urls/conf.py\", line 39, in include\n",
            "    urlconf_module = import_module(urlconf_module)\n",
            "  File \"/usr/lib/python3.10/importlib/__init__.py\", line 126, in import_module\n",
            "    return _bootstrap._gcd_import(name[level:], package, level)\n",
            "  File \"<frozen importlib._bootstrap>\", line 1050, in _gcd_import\n",
            "  File \"<frozen importlib._bootstrap>\", line 1027, in _find_and_load\n",
            "  File \"<frozen importlib._bootstrap>\", line 1006, in _find_and_load_unlocked\n",
            "  File \"<frozen importlib._bootstrap>\", line 688, in _load_unlocked\n",
            "  File \"<frozen importlib._bootstrap_external>\", line 883, in exec_module\n",
            "  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\n",
            "  File \"/content/diary_project/diary/urls.py\", line 3, in <module>\n",
            "    from .views import predict_view\n",
            "  File \"/content/diary_project/diary/views.py\", line 2, in <module>\n",
            "    from .depression_model import depression_predict\n",
            "  File \"/content/diary_project/diary/depression_model.py\", line 17, in <module>\n",
            "    model1 = BERTClassifier(bertmodel,  dr_rate = 0.5).to(device)\n",
            "NameError: name 'BERTClassifier' is not defined\n",
            "/content/diary_project/diary/depression_model.py changed, reloading.\n",
            "[Kss]: /content/diary_project/diary/depression_model.py changed, reloading.\n",
            "Watching for file changes with StatReloader\n",
            "Performing system checks...\n",
            "\n",
            "The tokenizer class you load from this checkpoint is not the same type as the class this function is called from. It may result in unexpected tokenization. \n",
            "The tokenizer class you load from this checkpoint is 'XLNetTokenizer'. \n",
            "The class this function is called from is 'KoBERTTokenizer'.\n",
            "The tokenizer class you load from this checkpoint is not the same type as the class this function is called from. It may result in unexpected tokenization. \n",
            "The tokenizer class you load from this checkpoint is 'XLNetTokenizer'. \n",
            "The class this function is called from is 'KoBERTTokenizer'.\n",
            "Exception in thread django-main-thread:\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/lib/python3.10/threading.py\", line 1016, in _bootstrap_inner\n",
            "    self.run()\n",
            "  File \"/usr/lib/python3.10/threading.py\", line 953, in run\n",
            "    self._target(*self._args, **self._kwargs)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/django/utils/autoreload.py\", line 64, in wrapper\n",
            "    fn(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/django/core/management/commands/runserver.py\", line 133, in inner_run\n",
            "    self.check(display_num_errors=True)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/django/core/management/base.py\", line 486, in check\n",
            "    all_issues = checks.run_checks(\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/django/core/checks/registry.py\", line 88, in run_checks\n",
            "    new_errors = check(app_configs=app_configs, databases=databases)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/django/core/checks/urls.py\", line 42, in check_url_namespaces_unique\n",
            "    all_namespaces = _load_all_namespaces(resolver)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/django/core/checks/urls.py\", line 61, in _load_all_namespaces\n",
            "    url_patterns = getattr(resolver, \"url_patterns\", [])\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/django/utils/functional.py\", line 47, in __get__\n",
            "    res = instance.__dict__[self.name] = self.func(instance)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/django/urls/resolvers.py\", line 738, in url_patterns\n",
            "    patterns = getattr(self.urlconf_module, \"urlpatterns\", self.urlconf_module)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/django/utils/functional.py\", line 47, in __get__\n",
            "    res = instance.__dict__[self.name] = self.func(instance)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/django/urls/resolvers.py\", line 731, in urlconf_module\n",
            "    return import_module(self.urlconf_name)\n",
            "  File \"/usr/lib/python3.10/importlib/__init__.py\", line 126, in import_module\n",
            "    return _bootstrap._gcd_import(name[level:], package, level)\n",
            "  File \"<frozen importlib._bootstrap>\", line 1050, in _gcd_import\n",
            "  File \"<frozen importlib._bootstrap>\", line 1027, in _find_and_load\n",
            "  File \"<frozen importlib._bootstrap>\", line 1006, in _find_and_load_unlocked\n",
            "  File \"<frozen importlib._bootstrap>\", line 688, in _load_unlocked\n",
            "  File \"<frozen importlib._bootstrap_external>\", line 883, in exec_module\n",
            "  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\n",
            "  File \"/content/diary_project/diary_project/urls.py\", line 22, in <module>\n",
            "    path('', include('diary.urls')),\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/django/urls/conf.py\", line 39, in include\n",
            "    urlconf_module = import_module(urlconf_module)\n",
            "  File \"/usr/lib/python3.10/importlib/__init__.py\", line 126, in import_module\n",
            "    return _bootstrap._gcd_import(name[level:], package, level)\n",
            "  File \"<frozen importlib._bootstrap>\", line 1050, in _gcd_import\n",
            "  File \"<frozen importlib._bootstrap>\", line 1027, in _find_and_load\n",
            "  File \"<frozen importlib._bootstrap>\", line 1006, in _find_and_load_unlocked\n",
            "  File \"<frozen importlib._bootstrap>\", line 688, in _load_unlocked\n",
            "  File \"<frozen importlib._bootstrap_external>\", line 883, in exec_module\n",
            "  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\n",
            "  File \"/content/diary_project/diary/urls.py\", line 3, in <module>\n",
            "    from .views import predict_view\n",
            "  File \"/content/diary_project/diary/views.py\", line 2, in <module>\n",
            "    from .depression_model import depression_predict\n",
            "  File \"/content/diary_project/diary/depression_model.py\", line 17, in <module>\n",
            "    model1 = BERTClassifier(bertmodel,  dr_rate = 0.5)\n",
            "NameError: name 'BERTClassifier' is not defined\n",
            "/content/diary_project/diary/depression_model.py changed, reloading.\n",
            "[Kss]: /content/diary_project/diary/depression_model.py changed, reloading.\n",
            "Watching for file changes with StatReloader\n",
            "Performing system checks...\n",
            "\n",
            "The tokenizer class you load from this checkpoint is not the same type as the class this function is called from. It may result in unexpected tokenization. \n",
            "The tokenizer class you load from this checkpoint is 'XLNetTokenizer'. \n",
            "The class this function is called from is 'KoBERTTokenizer'.\n",
            "System check identified no issues (0 silenced).\n",
            "\u001b[31m\n",
            "You have 18 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): admin, auth, contenttypes, sessions.\u001b[0m\n",
            "\u001b[31mRun 'python manage.py migrate' to apply them.\u001b[0m\n",
            "June 20, 2024 - 14:13:30\n",
            "Django version 5.0.6, using settings 'diary_project.settings'\n",
            "Starting development server at http://127.0.0.1:8000/\n",
            "Quit the server with CONTROL-C.\n",
            "\n",
            "Internal Server Error: /\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/django/core/handlers/exception.py\", line 55, in inner\n",
            "    response = get_response(request)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/django/core/handlers/base.py\", line 197, in _get_response\n",
            "    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n",
            "  File \"/content/diary_project/diary/views.py\", line 12, in predict_view\n",
            "    return render(request, 'diary.html', context)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/django/shortcuts.py\", line 25, in render\n",
            "    content = loader.render_to_string(template_name, context, request, using=using)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/django/template/loader.py\", line 62, in render_to_string\n",
            "    return template.render(context, request)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/django/template/backends/django.py\", line 61, in render\n",
            "    return self.template.render(context)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/django/template/base.py\", line 171, in render\n",
            "    return self._render(context)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/django/template/base.py\", line 163, in _render\n",
            "    return self.nodelist.render(context)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/django/template/base.py\", line 1000, in render\n",
            "    return SafeString(\"\".join([node.render_annotated(context) for node in self]))\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/django/template/base.py\", line 1000, in <listcomp>\n",
            "    return SafeString(\"\".join([node.render_annotated(context) for node in self]))\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/django/template/base.py\", line 961, in render_annotated\n",
            "    return self.render(context)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/django/template/defaulttags.py\", line 479, in render\n",
            "    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/django/urls/base.py\", line 88, in reverse\n",
            "    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/django/urls/resolvers.py\", line 851, in _reverse_with_prefix\n",
            "    raise NoReverseMatch(msg)\n",
            "django.urls.exceptions.NoReverseMatch: Reverse for 'predict_view' not found. 'predict_view' is not a valid view function or pattern name.\n",
            "[Kss]: Internal Server Error: /\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/django/core/handlers/exception.py\", line 55, in inner\n",
            "    response = get_response(request)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/django/core/handlers/base.py\", line 197, in _get_response\n",
            "    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n",
            "  File \"/content/diary_project/diary/views.py\", line 12, in predict_view\n",
            "    return render(request, 'diary.html', context)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/django/shortcuts.py\", line 25, in render\n",
            "    content = loader.render_to_string(template_name, context, request, using=using)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/django/template/loader.py\", line 62, in render_to_string\n",
            "    return template.render(context, request)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/django/template/backends/django.py\", line 61, in render\n",
            "    return self.template.render(context)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/django/template/base.py\", line 171, in render\n",
            "    return self._render(context)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/django/template/base.py\", line 163, in _render\n",
            "    return self.nodelist.render(context)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/django/template/base.py\", line 1000, in render\n",
            "    return SafeString(\"\".join([node.render_annotated(context) for node in self]))\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/django/template/base.py\", line 1000, in <listcomp>\n",
            "    return SafeString(\"\".join([node.render_annotated(context) for node in self]))\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/django/template/base.py\", line 961, in render_annotated\n",
            "    return self.render(context)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/django/template/defaulttags.py\", line 479, in render\n",
            "    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/django/urls/base.py\", line 88, in reverse\n",
            "    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/django/urls/resolvers.py\", line 851, in _reverse_with_prefix\n",
            "    raise NoReverseMatch(msg)\n",
            "django.urls.exceptions.NoReverseMatch: Reverse for 'predict_view' not found. 'predict_view' is not a valid view function or pattern name.\n",
            "[20/Jun/2024 14:13:37] \u001b[35;1m\"GET / HTTP/1.1\" 500 121594\u001b[0m\n",
            "/content/diary_project/diary/depression_model.py changed, reloading.\n",
            "[Kss]: /content/diary_project/diary/depression_model.py changed, reloading.\n",
            "Watching for file changes with StatReloader\n",
            "Performing system checks...\n",
            "\n",
            "The tokenizer class you load from this checkpoint is not the same type as the class this function is called from. It may result in unexpected tokenization. \n",
            "The tokenizer class you load from this checkpoint is 'XLNetTokenizer'. \n",
            "The class this function is called from is 'KoBERTTokenizer'.\n",
            "System check identified no issues (0 silenced).\n",
            "\u001b[31m\n",
            "You have 18 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): admin, auth, contenttypes, sessions.\u001b[0m\n",
            "\u001b[31mRun 'python manage.py migrate' to apply them.\u001b[0m\n",
            "June 20, 2024 - 14:13:59\n",
            "Django version 5.0.6, using settings 'diary_project.settings'\n",
            "Starting development server at http://127.0.0.1:8000/\n",
            "Quit the server with CONTROL-C.\n",
            "\n",
            "/content/diary_project/diary/views.py changed, reloading.\n",
            "[Kss]: /content/diary_project/diary/views.py changed, reloading.\n",
            "Watching for file changes with StatReloader\n",
            "Performing system checks...\n",
            "\n",
            "The tokenizer class you load from this checkpoint is not the same type as the class this function is called from. It may result in unexpected tokenization. \n",
            "The tokenizer class you load from this checkpoint is 'XLNetTokenizer'. \n",
            "The class this function is called from is 'KoBERTTokenizer'.\n",
            "System check identified no issues (0 silenced).\n",
            "\u001b[31m\n",
            "You have 18 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): admin, auth, contenttypes, sessions.\u001b[0m\n",
            "\u001b[31mRun 'python manage.py migrate' to apply them.\u001b[0m\n",
            "June 20, 2024 - 14:14:22\n",
            "Django version 5.0.6, using settings 'diary_project.settings'\n",
            "Starting development server at http://127.0.0.1:8000/\n",
            "Quit the server with CONTROL-C.\n",
            "\n",
            "Internal Server Error: /\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/django/core/handlers/exception.py\", line 55, in inner\n",
            "    response = get_response(request)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/django/core/handlers/base.py\", line 197, in _get_response\n",
            "    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n",
            "  File \"/content/diary_project/diary/views.py\", line 12, in predict_view\n",
            "    return render(request, 'diary.html', context)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/django/shortcuts.py\", line 25, in render\n",
            "    content = loader.render_to_string(template_name, context, request, using=using)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/django/template/loader.py\", line 62, in render_to_string\n",
            "    return template.render(context, request)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/django/template/backends/django.py\", line 61, in render\n",
            "    return self.template.render(context)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/django/template/base.py\", line 171, in render\n",
            "    return self._render(context)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/django/template/base.py\", line 163, in _render\n",
            "    return self.nodelist.render(context)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/django/template/base.py\", line 1000, in render\n",
            "    return SafeString(\"\".join([node.render_annotated(context) for node in self]))\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/django/template/base.py\", line 1000, in <listcomp>\n",
            "    return SafeString(\"\".join([node.render_annotated(context) for node in self]))\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/django/template/base.py\", line 961, in render_annotated\n",
            "    return self.render(context)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/django/template/defaulttags.py\", line 479, in render\n",
            "    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/django/urls/base.py\", line 88, in reverse\n",
            "    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/django/urls/resolvers.py\", line 851, in _reverse_with_prefix\n",
            "    raise NoReverseMatch(msg)\n",
            "django.urls.exceptions.NoReverseMatch: Reverse for 'predict_view' not found. 'predict_view' is not a valid view function or pattern name.\n",
            "[Kss]: Internal Server Error: /\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/django/core/handlers/exception.py\", line 55, in inner\n",
            "    response = get_response(request)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/django/core/handlers/base.py\", line 197, in _get_response\n",
            "    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n",
            "  File \"/content/diary_project/diary/views.py\", line 12, in predict_view\n",
            "    return render(request, 'diary.html', context)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/django/shortcuts.py\", line 25, in render\n",
            "    content = loader.render_to_string(template_name, context, request, using=using)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/django/template/loader.py\", line 62, in render_to_string\n",
            "    return template.render(context, request)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/django/template/backends/django.py\", line 61, in render\n",
            "    return self.template.render(context)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/django/template/base.py\", line 171, in render\n",
            "    return self._render(context)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/django/template/base.py\", line 163, in _render\n",
            "    return self.nodelist.render(context)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/django/template/base.py\", line 1000, in render\n",
            "    return SafeString(\"\".join([node.render_annotated(context) for node in self]))\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/django/template/base.py\", line 1000, in <listcomp>\n",
            "    return SafeString(\"\".join([node.render_annotated(context) for node in self]))\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/django/template/base.py\", line 961, in render_annotated\n",
            "    return self.render(context)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/django/template/defaulttags.py\", line 479, in render\n",
            "    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/django/urls/base.py\", line 88, in reverse\n",
            "    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/django/urls/resolvers.py\", line 851, in _reverse_with_prefix\n",
            "    raise NoReverseMatch(msg)\n",
            "django.urls.exceptions.NoReverseMatch: Reverse for 'predict_view' not found. 'predict_view' is not a valid view function or pattern name.\n",
            "[20/Jun/2024 14:14:33] \u001b[35;1m\"GET / HTTP/1.1\" 500 121594\u001b[0m\n",
            "/content/diary_project/diary/urls.py changed, reloading.\n",
            "[Kss]: /content/diary_project/diary/urls.py changed, reloading.\n",
            "Watching for file changes with StatReloader\n",
            "Performing system checks...\n",
            "\n",
            "The tokenizer class you load from this checkpoint is not the same type as the class this function is called from. It may result in unexpected tokenization. \n",
            "The tokenizer class you load from this checkpoint is 'XLNetTokenizer'. \n",
            "The class this function is called from is 'KoBERTTokenizer'.\n",
            "System check identified no issues (0 silenced).\n",
            "\u001b[31m\n",
            "You have 18 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): admin, auth, contenttypes, sessions.\u001b[0m\n",
            "\u001b[31mRun 'python manage.py migrate' to apply them.\u001b[0m\n",
            "June 20, 2024 - 14:14:52\n",
            "Django version 5.0.6, using settings 'diary_project.settings'\n",
            "Starting development server at http://127.0.0.1:8000/\n",
            "Quit the server with CONTROL-C.\n",
            "\n",
            "/content/diary_project/diary/urls.py changed, reloading.\n",
            "[Kss]: /content/diary_project/diary/urls.py changed, reloading.\n",
            "Watching for file changes with StatReloader\n",
            "Performing system checks...\n",
            "\n",
            "The tokenizer class you load from this checkpoint is not the same type as the class this function is called from. It may result in unexpected tokenization. \n",
            "The tokenizer class you load from this checkpoint is 'XLNetTokenizer'. \n",
            "The class this function is called from is 'KoBERTTokenizer'.\n",
            "Exception in thread django-main-thread:\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/lib/python3.10/threading.py\", line 1016, in _bootstrap_inner\n",
            "    self.run()\n",
            "  File \"/usr/lib/python3.10/threading.py\", line 953, in run\n",
            "    self._target(*self._args, **self._kwargs)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/django/utils/autoreload.py\", line 64, in wrapper\n",
            "    fn(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/django/core/management/commands/runserver.py\", line 133, in inner_run\n",
            "    self.check(display_num_errors=True)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/django/core/management/base.py\", line 486, in check\n",
            "    all_issues = checks.run_checks(\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/django/core/checks/registry.py\", line 88, in run_checks\n",
            "    new_errors = check(app_configs=app_configs, databases=databases)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/django/core/checks/urls.py\", line 42, in check_url_namespaces_unique\n",
            "    all_namespaces = _load_all_namespaces(resolver)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/django/core/checks/urls.py\", line 61, in _load_all_namespaces\n",
            "    url_patterns = getattr(resolver, \"url_patterns\", [])\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/django/utils/functional.py\", line 47, in __get__\n",
            "    res = instance.__dict__[self.name] = self.func(instance)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/django/urls/resolvers.py\", line 738, in url_patterns\n",
            "    patterns = getattr(self.urlconf_module, \"urlpatterns\", self.urlconf_module)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/django/utils/functional.py\", line 47, in __get__\n",
            "    res = instance.__dict__[self.name] = self.func(instance)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/django/urls/resolvers.py\", line 731, in urlconf_module\n",
            "    return import_module(self.urlconf_name)\n",
            "  File \"/usr/lib/python3.10/importlib/__init__.py\", line 126, in import_module\n",
            "    return _bootstrap._gcd_import(name[level:], package, level)\n",
            "  File \"<frozen importlib._bootstrap>\", line 1050, in _gcd_import\n",
            "  File \"<frozen importlib._bootstrap>\", line 1027, in _find_and_load\n",
            "  File \"<frozen importlib._bootstrap>\", line 1006, in _find_and_load_unlocked\n",
            "  File \"<frozen importlib._bootstrap>\", line 688, in _load_unlocked\n",
            "  File \"<frozen importlib._bootstrap_external>\", line 883, in exec_module\n",
            "  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\n",
            "  File \"/content/diary_project/diary_project/urls.py\", line 22, in <module>\n",
            "    path('', include('diary.urls')),\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/django/urls/conf.py\", line 39, in include\n",
            "    urlconf_module = import_module(urlconf_module)\n",
            "  File \"/usr/lib/python3.10/importlib/__init__.py\", line 126, in import_module\n",
            "    return _bootstrap._gcd_import(name[level:], package, level)\n",
            "  File \"<frozen importlib._bootstrap>\", line 1050, in _gcd_import\n",
            "  File \"<frozen importlib._bootstrap>\", line 1027, in _find_and_load\n",
            "  File \"<frozen importlib._bootstrap>\", line 1006, in _find_and_load_unlocked\n",
            "  File \"<frozen importlib._bootstrap>\", line 688, in _load_unlocked\n",
            "  File \"<frozen importlib._bootstrap_external>\", line 883, in exec_module\n",
            "  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\n",
            "  File \"/content/diary_project/diary/urls.py\", line 6, in <module>\n",
            "    path('', predict_view, name='predict'),\n",
            "NameError: name 'predict_view' is not defined\n",
            "/content/diary_project/diary/urls.py changed, reloading.\n",
            "[Kss]: /content/diary_project/diary/urls.py changed, reloading.\n",
            "Watching for file changes with StatReloader\n",
            "Performing system checks...\n",
            "\n",
            "The tokenizer class you load from this checkpoint is not the same type as the class this function is called from. It may result in unexpected tokenization. \n",
            "The tokenizer class you load from this checkpoint is 'XLNetTokenizer'. \n",
            "The class this function is called from is 'KoBERTTokenizer'.\n",
            "System check identified no issues (0 silenced).\n",
            "\u001b[31m\n",
            "You have 18 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): admin, auth, contenttypes, sessions.\u001b[0m\n",
            "\u001b[31mRun 'python manage.py migrate' to apply them.\u001b[0m\n",
            "June 20, 2024 - 14:15:45\n",
            "Django version 5.0.6, using settings 'diary_project.settings'\n",
            "Starting development server at http://127.0.0.1:8000/\n",
            "Quit the server with CONTROL-C.\n",
            "\n",
            "/content/diary_project/diary/views.py changed, reloading.\n",
            "[Kss]: /content/diary_project/diary/views.py changed, reloading.\n",
            "Watching for file changes with StatReloader\n",
            "Performing system checks...\n",
            "\n",
            "The tokenizer class you load from this checkpoint is not the same type as the class this function is called from. It may result in unexpected tokenization. \n",
            "The tokenizer class you load from this checkpoint is 'XLNetTokenizer'. \n",
            "The class this function is called from is 'KoBERTTokenizer'.\n",
            "System check identified no issues (0 silenced).\n",
            "\u001b[31m\n",
            "You have 18 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): admin, auth, contenttypes, sessions.\u001b[0m\n",
            "\u001b[31mRun 'python manage.py migrate' to apply them.\u001b[0m\n",
            "June 20, 2024 - 14:16:13\n",
            "Django version 5.0.6, using settings 'diary_project.settings'\n",
            "Starting development server at http://127.0.0.1:8000/\n",
            "Quit the server with CONTROL-C.\n",
            "\n",
            "[20/Jun/2024 14:16:31] \u001b[m\"GET / HTTP/1.1\" 200 472\u001b[0m\n",
            "Not Found: /favicon.ico\n",
            "[Kss]: Not Found: /favicon.ico\n",
            "[20/Jun/2024 14:16:31] \u001b[33m\"GET /favicon.ico HTTP/1.1\" 404 2289\u001b[0m\n",
            "Forbidden (Origin checking failed - https://colab.research.google.com does not match any trusted origins.): /\n",
            "[Kss]: Forbidden (Origin checking failed - https://colab.research.google.com does not match any trusted origins.): /\n",
            "[20/Jun/2024 14:16:38] \u001b[31;1m\"POST / HTTP/1.1\" 403 2580\u001b[0m\n",
            "/content/diary_project/diary/views.py changed, reloading.\n",
            "[Kss]: /content/diary_project/diary/views.py changed, reloading.\n",
            "Watching for file changes with StatReloader\n",
            "Performing system checks...\n",
            "\n",
            "The tokenizer class you load from this checkpoint is not the same type as the class this function is called from. It may result in unexpected tokenization. \n",
            "The tokenizer class you load from this checkpoint is 'XLNetTokenizer'. \n",
            "The class this function is called from is 'KoBERTTokenizer'.\n",
            "System check identified no issues (0 silenced).\n",
            "\u001b[31m\n",
            "You have 18 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): admin, auth, contenttypes, sessions.\u001b[0m\n",
            "\u001b[31mRun 'python manage.py migrate' to apply them.\u001b[0m\n",
            "June 20, 2024 - 14:19:27\n",
            "Django version 5.0.6, using settings 'diary_project.settings'\n",
            "Starting development server at http://127.0.0.1:8000/\n",
            "Quit the server with CONTROL-C.\n",
            "\n",
            "[20/Jun/2024 14:19:32] \u001b[m\"GET / HTTP/1.1\" 200 472\u001b[0m\n",
            "Not Found: /favicon.ico\n",
            "[Kss]: Not Found: /favicon.ico\n",
            "[20/Jun/2024 14:19:32] \u001b[33m\"GET /favicon.ico HTTP/1.1\" 404 2289\u001b[0m\n",
            "/content/diary_project/diary/views.py changed, reloading.\n",
            "[Kss]: /content/diary_project/diary/views.py changed, reloading.\n",
            "Watching for file changes with StatReloader\n",
            "Performing system checks...\n",
            "\n",
            "The tokenizer class you load from this checkpoint is not the same type as the class this function is called from. It may result in unexpected tokenization. \n",
            "The tokenizer class you load from this checkpoint is 'XLNetTokenizer'. \n",
            "The class this function is called from is 'KoBERTTokenizer'.\n",
            "System check identified no issues (0 silenced).\n",
            "\u001b[31m\n",
            "You have 18 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): admin, auth, contenttypes, sessions.\u001b[0m\n",
            "\u001b[31mRun 'python manage.py migrate' to apply them.\u001b[0m\n",
            "June 20, 2024 - 14:19:53\n",
            "Django version 5.0.6, using settings 'diary_project.settings'\n",
            "Starting development server at http://127.0.0.1:8000/\n",
            "Quit the server with CONTROL-C.\n",
            "\n",
            "[Kss]: Oh! You have mecab in your environment. Kss will take this as a backend! :D\n",
            "\n",
            "너무 힘들고 우울하다\n",
            "Internal Server Error: /\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/django/core/handlers/exception.py\", line 55, in inner\n",
            "    response = get_response(request)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/django/core/handlers/base.py\", line 197, in _get_response\n",
            "    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/django/views/decorators/csrf.py\", line 65, in _view_wrapper\n",
            "    return view_func(request, *args, **kwargs)\n",
            "  File \"/content/diary_project/diary/views.py\", line 11, in diary\n",
            "    prediction = depression_predict(user_input)\n",
            "  File \"/content/diary_project/diary/depression_model.py\", line 102, in depression_predict\n",
            "    i = predict(sent)\n",
            "  File \"/content/diary_project/diary/depression_model.py\", line 69, in predict\n",
            "    for batch_id, (token_ids, valid_length, segment_ids, label) in enumerate(test_dataloader):\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/torch/utils/data/dataloader.py\", line 631, in __next__\n",
            "    data = self._next_data()\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/torch/utils/data/dataloader.py\", line 674, in _next_data\n",
            "    index = self._next_index()  # may raise StopIteration\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/torch/utils/data/dataloader.py\", line 621, in _next_index\n",
            "    return next(self._sampler_iter)  # may raise StopIteration\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/torch/utils/data/sampler.py\", line 287, in __iter__\n",
            "    for idx in self.sampler:\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/torch/utils/data/sampler.py\", line 111, in __iter__\n",
            "    return iter(range(len(self.data_source)))\n",
            "TypeError: 'NoneType' object cannot be interpreted as an integer\n",
            "[Kss]: Internal Server Error: /\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/django/core/handlers/exception.py\", line 55, in inner\n",
            "    response = get_response(request)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/django/core/handlers/base.py\", line 197, in _get_response\n",
            "    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/django/views/decorators/csrf.py\", line 65, in _view_wrapper\n",
            "    return view_func(request, *args, **kwargs)\n",
            "  File \"/content/diary_project/diary/views.py\", line 11, in diary\n",
            "    prediction = depression_predict(user_input)\n",
            "  File \"/content/diary_project/diary/depression_model.py\", line 102, in depression_predict\n",
            "    i = predict(sent)\n",
            "  File \"/content/diary_project/diary/depression_model.py\", line 69, in predict\n",
            "    for batch_id, (token_ids, valid_length, segment_ids, label) in enumerate(test_dataloader):\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/torch/utils/data/dataloader.py\", line 631, in __next__\n",
            "    data = self._next_data()\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/torch/utils/data/dataloader.py\", line 674, in _next_data\n",
            "    index = self._next_index()  # may raise StopIteration\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/torch/utils/data/dataloader.py\", line 621, in _next_index\n",
            "    return next(self._sampler_iter)  # may raise StopIteration\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/torch/utils/data/sampler.py\", line 287, in __iter__\n",
            "    for idx in self.sampler:\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/torch/utils/data/sampler.py\", line 111, in __iter__\n",
            "    return iter(range(len(self.data_source)))\n",
            "TypeError: 'NoneType' object cannot be interpreted as an integer\n",
            "[20/Jun/2024 14:20:08] \u001b[35;1m\"POST / HTTP/1.1\" 500 102261\u001b[0m\n",
            "[20/Jun/2024 14:20:23] \u001b[m\"GET / HTTP/1.1\" 200 472\u001b[0m\n",
            "Not Found: /favicon.ico\n",
            "[Kss]: Not Found: /favicon.ico\n",
            "[20/Jun/2024 14:20:23] \u001b[33m\"GET /favicon.ico HTTP/1.1\" 404 2289\u001b[0m\n",
            "너무 힘들어\n",
            "Internal Server Error: /\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/django/core/handlers/exception.py\", line 55, in inner\n",
            "    response = get_response(request)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/django/core/handlers/base.py\", line 197, in _get_response\n",
            "    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/django/views/decorators/csrf.py\", line 65, in _view_wrapper\n",
            "    return view_func(request, *args, **kwargs)\n",
            "  File \"/content/diary_project/diary/views.py\", line 11, in diary\n",
            "    prediction = depression_predict(user_input)\n",
            "  File \"/content/diary_project/diary/depression_model.py\", line 102, in depression_predict\n",
            "    i = predict(sent)\n",
            "  File \"/content/diary_project/diary/depression_model.py\", line 69, in predict\n",
            "    for batch_id, (token_ids, valid_length, segment_ids, label) in enumerate(test_dataloader):\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/torch/utils/data/dataloader.py\", line 631, in __next__\n",
            "    data = self._next_data()\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/torch/utils/data/dataloader.py\", line 674, in _next_data\n",
            "    index = self._next_index()  # may raise StopIteration\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/torch/utils/data/dataloader.py\", line 621, in _next_index\n",
            "    return next(self._sampler_iter)  # may raise StopIteration\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/torch/utils/data/sampler.py\", line 287, in __iter__\n",
            "    for idx in self.sampler:\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/torch/utils/data/sampler.py\", line 111, in __iter__\n",
            "    return iter(range(len(self.data_source)))\n",
            "TypeError: 'NoneType' object cannot be interpreted as an integer\n",
            "[Kss]: Internal Server Error: /\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/django/core/handlers/exception.py\", line 55, in inner\n",
            "    response = get_response(request)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/django/core/handlers/base.py\", line 197, in _get_response\n",
            "    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/django/views/decorators/csrf.py\", line 65, in _view_wrapper\n",
            "    return view_func(request, *args, **kwargs)\n",
            "  File \"/content/diary_project/diary/views.py\", line 11, in diary\n",
            "    prediction = depression_predict(user_input)\n",
            "  File \"/content/diary_project/diary/depression_model.py\", line 102, in depression_predict\n",
            "    i = predict(sent)\n",
            "  File \"/content/diary_project/diary/depression_model.py\", line 69, in predict\n",
            "    for batch_id, (token_ids, valid_length, segment_ids, label) in enumerate(test_dataloader):\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/torch/utils/data/dataloader.py\", line 631, in __next__\n",
            "    data = self._next_data()\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/torch/utils/data/dataloader.py\", line 674, in _next_data\n",
            "    index = self._next_index()  # may raise StopIteration\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/torch/utils/data/dataloader.py\", line 621, in _next_index\n",
            "    return next(self._sampler_iter)  # may raise StopIteration\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/torch/utils/data/sampler.py\", line 287, in __iter__\n",
            "    for idx in self.sampler:\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/torch/utils/data/sampler.py\", line 111, in __iter__\n",
            "    return iter(range(len(self.data_source)))\n",
            "TypeError: 'NoneType' object cannot be interpreted as an integer\n",
            "[20/Jun/2024 14:20:28] \u001b[35;1m\"POST / HTTP/1.1\" 500 102157\u001b[0m\n",
            "/content/diary_project/diary/depression_model.py changed, reloading.\n",
            "[Kss]: /content/diary_project/diary/depression_model.py changed, reloading.\n",
            "Watching for file changes with StatReloader\n",
            "Performing system checks...\n",
            "\n",
            "The tokenizer class you load from this checkpoint is not the same type as the class this function is called from. It may result in unexpected tokenization. \n",
            "The tokenizer class you load from this checkpoint is 'XLNetTokenizer'. \n",
            "The class this function is called from is 'KoBERTTokenizer'.\n",
            "System check identified no issues (0 silenced).\n",
            "\u001b[31m\n",
            "You have 18 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): admin, auth, contenttypes, sessions.\u001b[0m\n",
            "\u001b[31mRun 'python manage.py migrate' to apply them.\u001b[0m\n",
            "June 20, 2024 - 14:27:12\n",
            "Django version 5.0.6, using settings 'diary_project.settings'\n",
            "Starting development server at http://127.0.0.1:8000/\n",
            "Quit the server with CONTROL-C.\n",
            "\n",
            "/content/diary_project/diary/depression_model.py changed, reloading.\n",
            "[Kss]: /content/diary_project/diary/depression_model.py changed, reloading.\n",
            "Watching for file changes with StatReloader\n",
            "Performing system checks...\n",
            "\n",
            "The tokenizer class you load from this checkpoint is not the same type as the class this function is called from. It may result in unexpected tokenization. \n",
            "The tokenizer class you load from this checkpoint is 'XLNetTokenizer'. \n",
            "The class this function is called from is 'KoBERTTokenizer'.\n",
            "System check identified no issues (0 silenced).\n",
            "\u001b[31m\n",
            "You have 18 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): admin, auth, contenttypes, sessions.\u001b[0m\n",
            "\u001b[31mRun 'python manage.py migrate' to apply them.\u001b[0m\n",
            "June 20, 2024 - 14:27:51\n",
            "Django version 5.0.6, using settings 'diary_project.settings'\n",
            "Starting development server at http://127.0.0.1:8000/\n",
            "Quit the server with CONTROL-C.\n",
            "\n",
            "/content/diary_project/diary/depression_model.py changed, reloading.\n",
            "[Kss]: /content/diary_project/diary/depression_model.py changed, reloading.\n",
            "Watching for file changes with StatReloader\n",
            "Performing system checks...\n",
            "\n",
            "The tokenizer class you load from this checkpoint is not the same type as the class this function is called from. It may result in unexpected tokenization. \n",
            "The tokenizer class you load from this checkpoint is 'XLNetTokenizer'. \n",
            "The class this function is called from is 'KoBERTTokenizer'.\n",
            "System check identified no issues (0 silenced).\n",
            "\u001b[31m\n",
            "You have 18 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): admin, auth, contenttypes, sessions.\u001b[0m\n",
            "\u001b[31mRun 'python manage.py migrate' to apply them.\u001b[0m\n",
            "June 20, 2024 - 14:32:50\n",
            "Django version 5.0.6, using settings 'diary_project.settings'\n",
            "Starting development server at http://127.0.0.1:8000/\n",
            "Quit the server with CONTROL-C.\n",
            "\n",
            "[20/Jun/2024 14:32:54] \u001b[m\"GET / HTTP/1.1\" 200 472\u001b[0m\n",
            "Not Found: /favicon.ico\n",
            "[Kss]: Not Found: /favicon.ico\n",
            "[20/Jun/2024 14:32:54] \u001b[33m\"GET /favicon.ico HTTP/1.1\" 404 2289\u001b[0m\n",
            "[Kss]: Oh! You have mecab in your environment. Kss will take this as a backend! :D\n",
            "\n",
            "너무 우울해\n",
            "Internal Server Error: /\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/django/core/handlers/exception.py\", line 55, in inner\n",
            "    response = get_response(request)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/django/core/handlers/base.py\", line 197, in _get_response\n",
            "    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/django/views/decorators/csrf.py\", line 65, in _view_wrapper\n",
            "    return view_func(request, *args, **kwargs)\n",
            "  File \"/content/diary_project/diary/views.py\", line 11, in diary\n",
            "    prediction = depression_predict(user_input)\n",
            "  File \"/content/diary_project/diary/depression_model.py\", line 104, in depression_predict\n",
            "    i = predict(sent)\n",
            "  File \"/content/diary_project/diary/depression_model.py\", line 75, in predict\n",
            "    out = model1(input_ids=token_ids, attention_mask=segment_ids, token_type_ids=segment_ids)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py\", line 1532, in _wrapped_call_impl\n",
            "    return self._call_impl(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py\", line 1541, in _call_impl\n",
            "    return forward_call(*args, **kwargs)\n",
            "TypeError: BERTClassifier.forward() got an unexpected keyword argument 'input_ids'\n",
            "[Kss]: Internal Server Error: /\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/django/core/handlers/exception.py\", line 55, in inner\n",
            "    response = get_response(request)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/django/core/handlers/base.py\", line 197, in _get_response\n",
            "    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/django/views/decorators/csrf.py\", line 65, in _view_wrapper\n",
            "    return view_func(request, *args, **kwargs)\n",
            "  File \"/content/diary_project/diary/views.py\", line 11, in diary\n",
            "    prediction = depression_predict(user_input)\n",
            "  File \"/content/diary_project/diary/depression_model.py\", line 104, in depression_predict\n",
            "    i = predict(sent)\n",
            "  File \"/content/diary_project/diary/depression_model.py\", line 75, in predict\n",
            "    out = model1(input_ids=token_ids, attention_mask=segment_ids, token_type_ids=segment_ids)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py\", line 1532, in _wrapped_call_impl\n",
            "    return self._call_impl(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py\", line 1541, in _call_impl\n",
            "    return forward_call(*args, **kwargs)\n",
            "TypeError: BERTClassifier.forward() got an unexpected keyword argument 'input_ids'\n",
            "[20/Jun/2024 14:33:03] \u001b[35;1m\"POST / HTTP/1.1\" 500 100555\u001b[0m\n",
            "/content/diary_project/diary/depression_model.py changed, reloading.\n",
            "[Kss]: /content/diary_project/diary/depression_model.py changed, reloading.\n",
            "Watching for file changes with StatReloader\n",
            "Performing system checks...\n",
            "\n",
            "Exception in thread django-main-thread:\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/lib/python3.10/threading.py\", line 1016, in _bootstrap_inner\n",
            "    self.run()\n",
            "  File \"/usr/lib/python3.10/threading.py\", line 953, in run\n",
            "    self._target(*self._args, **self._kwargs)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/django/utils/autoreload.py\", line 64, in wrapper\n",
            "    fn(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/django/core/management/commands/runserver.py\", line 133, in inner_run\n",
            "    self.check(display_num_errors=True)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/django/core/management/base.py\", line 486, in check\n",
            "    all_issues = checks.run_checks(\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/django/core/checks/registry.py\", line 88, in run_checks\n",
            "    new_errors = check(app_configs=app_configs, databases=databases)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/django/core/checks/urls.py\", line 42, in check_url_namespaces_unique\n",
            "    all_namespaces = _load_all_namespaces(resolver)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/django/core/checks/urls.py\", line 61, in _load_all_namespaces\n",
            "    url_patterns = getattr(resolver, \"url_patterns\", [])\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/django/utils/functional.py\", line 47, in __get__\n",
            "    res = instance.__dict__[self.name] = self.func(instance)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/django/urls/resolvers.py\", line 738, in url_patterns\n",
            "    patterns = getattr(self.urlconf_module, \"urlpatterns\", self.urlconf_module)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/django/utils/functional.py\", line 47, in __get__\n",
            "    res = instance.__dict__[self.name] = self.func(instance)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/django/urls/resolvers.py\", line 731, in urlconf_module\n",
            "    return import_module(self.urlconf_name)\n",
            "  File \"/usr/lib/python3.10/importlib/__init__.py\", line 126, in import_module\n",
            "    return _bootstrap._gcd_import(name[level:], package, level)\n",
            "  File \"<frozen importlib._bootstrap>\", line 1050, in _gcd_import\n",
            "  File \"<frozen importlib._bootstrap>\", line 1027, in _find_and_load\n",
            "  File \"<frozen importlib._bootstrap>\", line 1006, in _find_and_load_unlocked\n",
            "  File \"<frozen importlib._bootstrap>\", line 688, in _load_unlocked\n",
            "  File \"<frozen importlib._bootstrap_external>\", line 883, in exec_module\n",
            "  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\n",
            "  File \"/content/diary_project/diary_project/urls.py\", line 22, in <module>\n",
            "    path('', include('diary.urls')),\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/django/urls/conf.py\", line 39, in include\n",
            "    urlconf_module = import_module(urlconf_module)\n",
            "  File \"/usr/lib/python3.10/importlib/__init__.py\", line 126, in import_module\n",
            "    return _bootstrap._gcd_import(name[level:], package, level)\n",
            "  File \"<frozen importlib._bootstrap>\", line 1050, in _gcd_import\n",
            "  File \"<frozen importlib._bootstrap>\", line 1027, in _find_and_load\n",
            "  File \"<frozen importlib._bootstrap>\", line 1006, in _find_and_load_unlocked\n",
            "  File \"<frozen importlib._bootstrap>\", line 688, in _load_unlocked\n",
            "  File \"<frozen importlib._bootstrap_external>\", line 883, in exec_module\n",
            "  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\n",
            "  File \"/content/diary_project/diary/urls.py\", line 3, in <module>\n",
            "    from . import views\n",
            "  File \"/content/diary_project/diary/views.py\", line 2, in <module>\n",
            "    from .depression_model import depression_predict\n",
            "  File \"/content/diary_project/diary/depression_model.py\", line 47\n",
            "    def __init__(self, dataset, sent_idx, label_idx, bert_tokenizer, vocab, max_len, pad, pair):\n",
            "IndentationError: unexpected indent\n",
            "/content/diary_project/diary/depression_model.py changed, reloading.\n",
            "Watching for file changes with StatReloader\n",
            "Performing system checks...\n",
            "\n",
            "Exception in thread django-main-thread:\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/lib/python3.10/threading.py\", line 1016, in _bootstrap_inner\n",
            "    self.run()\n",
            "  File \"/usr/lib/python3.10/threading.py\", line 953, in run\n",
            "    self._target(*self._args, **self._kwargs)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/django/utils/autoreload.py\", line 64, in wrapper\n",
            "    fn(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/django/core/management/commands/runserver.py\", line 133, in inner_run\n",
            "    self.check(display_num_errors=True)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/django/core/management/base.py\", line 486, in check\n",
            "    all_issues = checks.run_checks(\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/django/core/checks/registry.py\", line 88, in run_checks\n",
            "    new_errors = check(app_configs=app_configs, databases=databases)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/django/core/checks/urls.py\", line 42, in check_url_namespaces_unique\n",
            "    all_namespaces = _load_all_namespaces(resolver)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/django/core/checks/urls.py\", line 61, in _load_all_namespaces\n",
            "    url_patterns = getattr(resolver, \"url_patterns\", [])\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/django/utils/functional.py\", line 47, in __get__\n",
            "    res = instance.__dict__[self.name] = self.func(instance)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/django/urls/resolvers.py\", line 738, in url_patterns\n",
            "    patterns = getattr(self.urlconf_module, \"urlpatterns\", self.urlconf_module)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/django/utils/functional.py\", line 47, in __get__\n",
            "    res = instance.__dict__[self.name] = self.func(instance)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/django/urls/resolvers.py\", line 731, in urlconf_module\n",
            "    return import_module(self.urlconf_name)\n",
            "  File \"/usr/lib/python3.10/importlib/__init__.py\", line 126, in import_module\n",
            "    return _bootstrap._gcd_import(name[level:], package, level)\n",
            "  File \"<frozen importlib._bootstrap>\", line 1050, in _gcd_import\n",
            "  File \"<frozen importlib._bootstrap>\", line 1027, in _find_and_load\n",
            "  File \"<frozen importlib._bootstrap>\", line 1006, in _find_and_load_unlocked\n",
            "  File \"<frozen importlib._bootstrap>\", line 688, in _load_unlocked\n",
            "  File \"<frozen importlib._bootstrap_external>\", line 883, in exec_module\n",
            "  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\n",
            "  File \"/content/diary_project/diary_project/urls.py\", line 22, in <module>\n",
            "    path('', include('diary.urls')),\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/django/urls/conf.py\", line 39, in include\n",
            "    urlconf_module = import_module(urlconf_module)\n",
            "  File \"/usr/lib/python3.10/importlib/__init__.py\", line 126, in import_module\n",
            "    return _bootstrap._gcd_import(name[level:], package, level)\n",
            "  File \"<frozen importlib._bootstrap>\", line 1050, in _gcd_import\n",
            "  File \"<frozen importlib._bootstrap>\", line 1027, in _find_and_load\n",
            "  File \"<frozen importlib._bootstrap>\", line 1006, in _find_and_load_unlocked\n",
            "  File \"<frozen importlib._bootstrap>\", line 688, in _load_unlocked\n",
            "  File \"<frozen importlib._bootstrap_external>\", line 883, in exec_module\n",
            "  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\n",
            "  File \"/content/diary_project/diary/urls.py\", line 3, in <module>\n",
            "    from . import views\n",
            "  File \"/content/diary_project/diary/views.py\", line 2, in <module>\n",
            "    from .depression_model import depression_predict\n",
            "  File \"/content/diary_project/diary/depression_model.py\", line 47\n",
            "    def __init__(self, dataset, sent_idx, label_idx, bert_tokenizer, vocab, max_len, pad, pair):\n",
            "IndentationError: unexpected indent\n",
            "/content/diary_project/diary/depression_model.py changed, reloading.\n",
            "Watching for file changes with StatReloader\n",
            "Performing system checks...\n",
            "\n",
            "The tokenizer class you load from this checkpoint is not the same type as the class this function is called from. It may result in unexpected tokenization. \n",
            "The tokenizer class you load from this checkpoint is 'XLNetTokenizer'. \n",
            "The class this function is called from is 'KoBERTTokenizer'.\n",
            "System check identified no issues (0 silenced).\n",
            "\u001b[31m\n",
            "You have 18 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): admin, auth, contenttypes, sessions.\u001b[0m\n",
            "\u001b[31mRun 'python manage.py migrate' to apply them.\u001b[0m\n",
            "June 20, 2024 - 14:36:25\n",
            "Django version 5.0.6, using settings 'diary_project.settings'\n",
            "Starting development server at http://127.0.0.1:8000/\n",
            "Quit the server with CONTROL-C.\n",
            "\n",
            "[20/Jun/2024 14:36:40] \u001b[m\"GET / HTTP/1.1\" 200 472\u001b[0m\n",
            "Not Found: /favicon.ico\n",
            "[Kss]: Not Found: /favicon.ico\n",
            "[20/Jun/2024 14:36:40] \u001b[33m\"GET /favicon.ico HTTP/1.1\" 404 2289\u001b[0m\n",
            "/content/diary_project/diary/depression_model.py changed, reloading.\n",
            "[Kss]: /content/diary_project/diary/depression_model.py changed, reloading.\n",
            "Watching for file changes with StatReloader\n",
            "Performing system checks...\n",
            "\n",
            "The tokenizer class you load from this checkpoint is not the same type as the class this function is called from. It may result in unexpected tokenization. \n",
            "The tokenizer class you load from this checkpoint is 'XLNetTokenizer'. \n",
            "The class this function is called from is 'KoBERTTokenizer'.\n",
            "System check identified no issues (0 silenced).\n",
            "\u001b[31m\n",
            "You have 18 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): admin, auth, contenttypes, sessions.\u001b[0m\n",
            "\u001b[31mRun 'python manage.py migrate' to apply them.\u001b[0m\n",
            "June 20, 2024 - 14:37:01\n",
            "Django version 5.0.6, using settings 'diary_project.settings'\n",
            "Starting development server at http://127.0.0.1:8000/\n",
            "Quit the server with CONTROL-C.\n",
            "\n",
            "[20/Jun/2024 14:37:35] \u001b[m\"GET / HTTP/1.1\" 200 472\u001b[0m\n",
            "Not Found: /favicon.ico\n",
            "[Kss]: Not Found: /favicon.ico\n",
            "[20/Jun/2024 14:37:35] \u001b[33m\"GET /favicon.ico HTTP/1.1\" 404 2289\u001b[0m\n",
            "[Kss]: Oh! You have mecab in your environment. Kss will take this as a backend! :D\n",
            "\n",
            "너무 힘들고 아파\n",
            "Internal Server Error: /\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/django/core/handlers/exception.py\", line 55, in inner\n",
            "    response = get_response(request)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/django/core/handlers/base.py\", line 197, in _get_response\n",
            "    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/django/views/decorators/csrf.py\", line 65, in _view_wrapper\n",
            "    return view_func(request, *args, **kwargs)\n",
            "  File \"/content/diary_project/diary/views.py\", line 11, in diary\n",
            "    prediction = depression_predict(user_input)\n",
            "  File \"/content/diary_project/diary/depression_model.py\", line 106, in depression_predict\n",
            "    i = predict(sent)\n",
            "  File \"/content/diary_project/diary/depression_model.py\", line 76, in predict\n",
            "    out = model1(input_ids=input_ids, attention_mask=attention_mask, token_type_ids=token_type_ids)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py\", line 1532, in _wrapped_call_impl\n",
            "    return self._call_impl(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py\", line 1541, in _call_impl\n",
            "    return forward_call(*args, **kwargs)\n",
            "TypeError: BERTClassifier.forward() got an unexpected keyword argument 'input_ids'\n",
            "[Kss]: Internal Server Error: /\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/django/core/handlers/exception.py\", line 55, in inner\n",
            "    response = get_response(request)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/django/core/handlers/base.py\", line 197, in _get_response\n",
            "    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/django/views/decorators/csrf.py\", line 65, in _view_wrapper\n",
            "    return view_func(request, *args, **kwargs)\n",
            "  File \"/content/diary_project/diary/views.py\", line 11, in diary\n",
            "    prediction = depression_predict(user_input)\n",
            "  File \"/content/diary_project/diary/depression_model.py\", line 106, in depression_predict\n",
            "    i = predict(sent)\n",
            "  File \"/content/diary_project/diary/depression_model.py\", line 76, in predict\n",
            "    out = model1(input_ids=input_ids, attention_mask=attention_mask, token_type_ids=token_type_ids)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py\", line 1532, in _wrapped_call_impl\n",
            "    return self._call_impl(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py\", line 1541, in _call_impl\n",
            "    return forward_call(*args, **kwargs)\n",
            "TypeError: BERTClassifier.forward() got an unexpected keyword argument 'input_ids'\n",
            "[20/Jun/2024 14:37:47] \u001b[35;1m\"POST / HTTP/1.1\" 500 100696\u001b[0m\n",
            "/content/diary_project/diary/depression_model.py changed, reloading.\n",
            "[Kss]: /content/diary_project/diary/depression_model.py changed, reloading.\n",
            "Watching for file changes with StatReloader\n",
            "Performing system checks...\n",
            "\n",
            "The tokenizer class you load from this checkpoint is not the same type as the class this function is called from. It may result in unexpected tokenization. \n",
            "The tokenizer class you load from this checkpoint is 'XLNetTokenizer'. \n",
            "The class this function is called from is 'KoBERTTokenizer'.\n",
            "System check identified no issues (0 silenced).\n",
            "\u001b[31m\n",
            "You have 18 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): admin, auth, contenttypes, sessions.\u001b[0m\n",
            "\u001b[31mRun 'python manage.py migrate' to apply them.\u001b[0m\n",
            "June 20, 2024 - 14:38:21\n",
            "Django version 5.0.6, using settings 'diary_project.settings'\n",
            "Starting development server at http://127.0.0.1:8000/\n",
            "Quit the server with CONTROL-C.\n",
            "\n",
            "/content/diary_project/diary/depression_model.py changed, reloading.\n",
            "[Kss]: /content/diary_project/diary/depression_model.py changed, reloading.\n",
            "Watching for file changes with StatReloader\n",
            "Performing system checks...\n",
            "\n",
            "The tokenizer class you load from this checkpoint is not the same type as the class this function is called from. It may result in unexpected tokenization. \n",
            "The tokenizer class you load from this checkpoint is 'XLNetTokenizer'. \n",
            "The class this function is called from is 'KoBERTTokenizer'.\n",
            "System check identified no issues (0 silenced).\n",
            "\u001b[31m\n",
            "You have 18 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): admin, auth, contenttypes, sessions.\u001b[0m\n",
            "\u001b[31mRun 'python manage.py migrate' to apply them.\u001b[0m\n",
            "June 20, 2024 - 14:39:03\n",
            "Django version 5.0.6, using settings 'diary_project.settings'\n",
            "Starting development server at http://127.0.0.1:8000/\n",
            "Quit the server with CONTROL-C.\n",
            "\n",
            "[20/Jun/2024 14:39:24] \u001b[m\"GET / HTTP/1.1\" 200 472\u001b[0m\n",
            "Not Found: /favicon.ico\n",
            "[Kss]: Not Found: /favicon.ico\n",
            "[20/Jun/2024 14:39:24] \u001b[33m\"GET /favicon.ico HTTP/1.1\" 404 2289\u001b[0m\n",
            "/content/diary_project/diary/depression_model.py changed, reloading.\n",
            "[Kss]: /content/diary_project/diary/depression_model.py changed, reloading.\n",
            "Watching for file changes with StatReloader\n",
            "Performing system checks...\n",
            "\n",
            "The tokenizer class you load from this checkpoint is not the same type as the class this function is called from. It may result in unexpected tokenization. \n",
            "The tokenizer class you load from this checkpoint is 'XLNetTokenizer'. \n",
            "The class this function is called from is 'KoBERTTokenizer'.\n",
            "System check identified no issues (0 silenced).\n",
            "\u001b[31m\n",
            "You have 18 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): admin, auth, contenttypes, sessions.\u001b[0m\n",
            "\u001b[31mRun 'python manage.py migrate' to apply them.\u001b[0m\n",
            "June 20, 2024 - 14:39:46\n",
            "Django version 5.0.6, using settings 'diary_project.settings'\n",
            "Starting development server at http://127.0.0.1:8000/\n",
            "Quit the server with CONTROL-C.\n",
            "\n",
            "/content/diary_project/diary/depression_model.py changed, reloading.\n",
            "[Kss]: /content/diary_project/diary/depression_model.py changed, reloading.\n",
            "Watching for file changes with StatReloader\n",
            "Performing system checks...\n",
            "\n",
            "The tokenizer class you load from this checkpoint is not the same type as the class this function is called from. It may result in unexpected tokenization. \n",
            "The tokenizer class you load from this checkpoint is 'XLNetTokenizer'. \n",
            "The class this function is called from is 'KoBERTTokenizer'.\n",
            "System check identified no issues (0 silenced).\n",
            "\u001b[31m\n",
            "You have 18 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): admin, auth, contenttypes, sessions.\u001b[0m\n",
            "\u001b[31mRun 'python manage.py migrate' to apply them.\u001b[0m\n",
            "June 20, 2024 - 14:41:24\n",
            "Django version 5.0.6, using settings 'diary_project.settings'\n",
            "Starting development server at http://127.0.0.1:8000/\n",
            "Quit the server with CONTROL-C.\n",
            "\n",
            "/content/diary_project/diary/depression_model.py changed, reloading.\n",
            "[Kss]: /content/diary_project/diary/depression_model.py changed, reloading.\n",
            "Watching for file changes with StatReloader\n",
            "Performing system checks...\n",
            "\n",
            "The tokenizer class you load from this checkpoint is not the same type as the class this function is called from. It may result in unexpected tokenization. \n",
            "The tokenizer class you load from this checkpoint is 'XLNetTokenizer'. \n",
            "The class this function is called from is 'KoBERTTokenizer'.\n",
            "System check identified no issues (0 silenced).\n",
            "\u001b[31m\n",
            "You have 18 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): admin, auth, contenttypes, sessions.\u001b[0m\n",
            "\u001b[31mRun 'python manage.py migrate' to apply them.\u001b[0m\n",
            "June 20, 2024 - 14:43:02\n",
            "Django version 5.0.6, using settings 'diary_project.settings'\n",
            "Starting development server at http://127.0.0.1:8000/\n",
            "Quit the server with CONTROL-C.\n",
            "\n",
            "[20/Jun/2024 14:43:08] \u001b[m\"GET / HTTP/1.1\" 200 472\u001b[0m\n",
            "Not Found: /favicon.ico\n",
            "[Kss]: Not Found: /favicon.ico\n",
            "[20/Jun/2024 14:43:09] \u001b[33m\"GET /favicon.ico HTTP/1.1\" 404 2289\u001b[0m\n",
            "/content/diary_project/diary/depression_model.py changed, reloading.\n",
            "[Kss]: /content/diary_project/diary/depression_model.py changed, reloading.\n",
            "Watching for file changes with StatReloader\n",
            "Performing system checks...\n",
            "\n",
            "The tokenizer class you load from this checkpoint is not the same type as the class this function is called from. It may result in unexpected tokenization. \n",
            "The tokenizer class you load from this checkpoint is 'XLNetTokenizer'. \n",
            "The class this function is called from is 'KoBERTTokenizer'.\n",
            "System check identified no issues (0 silenced).\n",
            "\u001b[31m\n",
            "You have 18 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): admin, auth, contenttypes, sessions.\u001b[0m\n",
            "\u001b[31mRun 'python manage.py migrate' to apply them.\u001b[0m\n",
            "June 20, 2024 - 14:43:29\n",
            "Django version 5.0.6, using settings 'diary_project.settings'\n",
            "Starting development server at http://127.0.0.1:8000/\n",
            "Quit the server with CONTROL-C.\n",
            "\n",
            "[20/Jun/2024 14:43:37] \u001b[m\"GET / HTTP/1.1\" 200 472\u001b[0m\n",
            "Not Found: /favicon.ico\n",
            "[Kss]: Not Found: /favicon.ico\n",
            "[20/Jun/2024 14:43:37] \u001b[33m\"GET /favicon.ico HTTP/1.1\" 404 2289\u001b[0m\n",
            "[Kss]: Oh! You have mecab in your environment. Kss will take this as a backend! :D\n",
            "\n",
            "너무 우울하다\n",
            "Internal Server Error: /\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/django/core/handlers/exception.py\", line 55, in inner\n",
            "    response = get_response(request)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/django/core/handlers/base.py\", line 197, in _get_response\n",
            "    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/django/views/decorators/csrf.py\", line 65, in _view_wrapper\n",
            "    return view_func(request, *args, **kwargs)\n",
            "  File \"/content/diary_project/diary/views.py\", line 11, in diary\n",
            "    prediction = depression_predict(user_input)\n",
            "  File \"/content/diary_project/diary/depression_model.py\", line 104, in depression_predict\n",
            "    i = predict(sent)\n",
            "  File \"/content/diary_project/diary/depression_model.py\", line 77, in predict\n",
            "    for i in out.last_hidden_state:  # BERT 모델의 마지막 은닉 상태 사용\n",
            "AttributeError: 'Tensor' object has no attribute 'last_hidden_state'\n",
            "[Kss]: Internal Server Error: /\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/django/core/handlers/exception.py\", line 55, in inner\n",
            "    response = get_response(request)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/django/core/handlers/base.py\", line 197, in _get_response\n",
            "    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/django/views/decorators/csrf.py\", line 65, in _view_wrapper\n",
            "    return view_func(request, *args, **kwargs)\n",
            "  File \"/content/diary_project/diary/views.py\", line 11, in diary\n",
            "    prediction = depression_predict(user_input)\n",
            "  File \"/content/diary_project/diary/depression_model.py\", line 104, in depression_predict\n",
            "    i = predict(sent)\n",
            "  File \"/content/diary_project/diary/depression_model.py\", line 77, in predict\n",
            "    for i in out.last_hidden_state:  # BERT 모델의 마지막 은닉 상태 사용\n",
            "AttributeError: 'Tensor' object has no attribute 'last_hidden_state'\n",
            "[20/Jun/2024 14:43:45] \u001b[35;1m\"POST / HTTP/1.1\" 500 85196\u001b[0m\n",
            "/content/diary_project/diary/depression_model.py changed, reloading.\n",
            "[Kss]: /content/diary_project/diary/depression_model.py changed, reloading.\n",
            "Watching for file changes with StatReloader\n",
            "Performing system checks...\n",
            "\n",
            "Exception in thread django-main-thread:\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/lib/python3.10/threading.py\", line 1016, in _bootstrap_inner\n",
            "    self.run()\n",
            "  File \"/usr/lib/python3.10/threading.py\", line 953, in run\n",
            "    self._target(*self._args, **self._kwargs)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/django/utils/autoreload.py\", line 64, in wrapper\n",
            "    fn(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/django/core/management/commands/runserver.py\", line 133, in inner_run\n",
            "    self.check(display_num_errors=True)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/django/core/management/base.py\", line 486, in check\n",
            "    all_issues = checks.run_checks(\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/django/core/checks/registry.py\", line 88, in run_checks\n",
            "    new_errors = check(app_configs=app_configs, databases=databases)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/django/core/checks/urls.py\", line 42, in check_url_namespaces_unique\n",
            "    all_namespaces = _load_all_namespaces(resolver)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/django/core/checks/urls.py\", line 61, in _load_all_namespaces\n",
            "    url_patterns = getattr(resolver, \"url_patterns\", [])\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/django/utils/functional.py\", line 47, in __get__\n",
            "    res = instance.__dict__[self.name] = self.func(instance)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/django/urls/resolvers.py\", line 738, in url_patterns\n",
            "    patterns = getattr(self.urlconf_module, \"urlpatterns\", self.urlconf_module)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/django/utils/functional.py\", line 47, in __get__\n",
            "    res = instance.__dict__[self.name] = self.func(instance)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/django/urls/resolvers.py\", line 731, in urlconf_module\n",
            "    return import_module(self.urlconf_name)\n",
            "  File \"/usr/lib/python3.10/importlib/__init__.py\", line 126, in import_module\n",
            "    return _bootstrap._gcd_import(name[level:], package, level)\n",
            "  File \"<frozen importlib._bootstrap>\", line 1050, in _gcd_import\n",
            "  File \"<frozen importlib._bootstrap>\", line 1027, in _find_and_load\n",
            "  File \"<frozen importlib._bootstrap>\", line 1006, in _find_and_load_unlocked\n",
            "  File \"<frozen importlib._bootstrap>\", line 688, in _load_unlocked\n",
            "  File \"<frozen importlib._bootstrap_external>\", line 883, in exec_module\n",
            "  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\n",
            "  File \"/content/diary_project/diary_project/urls.py\", line 22, in <module>\n",
            "    path('', include('diary.urls')),\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/django/urls/conf.py\", line 39, in include\n",
            "    urlconf_module = import_module(urlconf_module)\n",
            "  File \"/usr/lib/python3.10/importlib/__init__.py\", line 126, in import_module\n",
            "    return _bootstrap._gcd_import(name[level:], package, level)\n",
            "  File \"<frozen importlib._bootstrap>\", line 1050, in _gcd_import\n",
            "  File \"<frozen importlib._bootstrap>\", line 1027, in _find_and_load\n",
            "  File \"<frozen importlib._bootstrap>\", line 1006, in _find_and_load_unlocked\n",
            "  File \"<frozen importlib._bootstrap>\", line 688, in _load_unlocked\n",
            "  File \"<frozen importlib._bootstrap_external>\", line 883, in exec_module\n",
            "  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\n",
            "  File \"/content/diary_project/diary/urls.py\", line 3, in <module>\n",
            "    from . import views\n",
            "  File \"/content/diary_project/diary/views.py\", line 2, in <module>\n",
            "    from .depression_model import depression_predict\n",
            "  File \"/content/diary_project/diary/depression_model.py\", line 69\n",
            "    input_ids = input_ids.long().to(device)\n",
            "    ^\n",
            "IndentationError: expected an indented block after 'for' statement on line 68\n",
            "/content/diary_project/diary/depression_model.py changed, reloading.\n",
            "Watching for file changes with StatReloader\n",
            "Performing system checks...\n",
            "\n",
            "Exception in thread django-main-thread:\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/lib/python3.10/threading.py\", line 1016, in _bootstrap_inner\n",
            "    self.run()\n",
            "  File \"/usr/lib/python3.10/threading.py\", line 953, in run\n",
            "    self._target(*self._args, **self._kwargs)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/django/utils/autoreload.py\", line 64, in wrapper\n",
            "    fn(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/django/core/management/commands/runserver.py\", line 133, in inner_run\n",
            "    self.check(display_num_errors=True)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/django/core/management/base.py\", line 486, in check\n",
            "    all_issues = checks.run_checks(\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/django/core/checks/registry.py\", line 88, in run_checks\n",
            "    new_errors = check(app_configs=app_configs, databases=databases)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/django/core/checks/urls.py\", line 42, in check_url_namespaces_unique\n",
            "    all_namespaces = _load_all_namespaces(resolver)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/django/core/checks/urls.py\", line 61, in _load_all_namespaces\n",
            "    url_patterns = getattr(resolver, \"url_patterns\", [])\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/django/utils/functional.py\", line 47, in __get__\n",
            "    res = instance.__dict__[self.name] = self.func(instance)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/django/urls/resolvers.py\", line 738, in url_patterns\n",
            "    patterns = getattr(self.urlconf_module, \"urlpatterns\", self.urlconf_module)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/django/utils/functional.py\", line 47, in __get__\n",
            "    res = instance.__dict__[self.name] = self.func(instance)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/django/urls/resolvers.py\", line 731, in urlconf_module\n",
            "    return import_module(self.urlconf_name)\n",
            "  File \"/usr/lib/python3.10/importlib/__init__.py\", line 126, in import_module\n",
            "    return _bootstrap._gcd_import(name[level:], package, level)\n",
            "  File \"<frozen importlib._bootstrap>\", line 1050, in _gcd_import\n",
            "  File \"<frozen importlib._bootstrap>\", line 1027, in _find_and_load\n",
            "  File \"<frozen importlib._bootstrap>\", line 1006, in _find_and_load_unlocked\n",
            "  File \"<frozen importlib._bootstrap>\", line 688, in _load_unlocked\n",
            "  File \"<frozen importlib._bootstrap_external>\", line 883, in exec_module\n",
            "  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\n",
            "  File \"/content/diary_project/diary_project/urls.py\", line 22, in <module>\n",
            "    path('', include('diary.urls')),\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/django/urls/conf.py\", line 39, in include\n",
            "    urlconf_module = import_module(urlconf_module)\n",
            "  File \"/usr/lib/python3.10/importlib/__init__.py\", line 126, in import_module\n",
            "    return _bootstrap._gcd_import(name[level:], package, level)\n",
            "  File \"<frozen importlib._bootstrap>\", line 1050, in _gcd_import\n",
            "  File \"<frozen importlib._bootstrap>\", line 1027, in _find_and_load\n",
            "  File \"<frozen importlib._bootstrap>\", line 1006, in _find_and_load_unlocked\n",
            "  File \"<frozen importlib._bootstrap>\", line 688, in _load_unlocked\n",
            "  File \"<frozen importlib._bootstrap_external>\", line 883, in exec_module\n",
            "  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\n",
            "  File \"/content/diary_project/diary/urls.py\", line 3, in <module>\n",
            "    from . import views\n",
            "  File \"/content/diary_project/diary/views.py\", line 2, in <module>\n",
            "    from .depression_model import depression_predict\n",
            "  File \"/content/diary_project/diary/depression_model.py\", line 69\n",
            "    input_ids = input_ids.long().to(device)\n",
            "    ^\n",
            "IndentationError: expected an indented block after 'for' statement on line 68\n",
            "/content/diary_project/diary/depression_model.py changed, reloading.\n",
            "Watching for file changes with StatReloader\n",
            "Performing system checks...\n",
            "\n",
            "Exception in thread django-main-thread:\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/lib/python3.10/threading.py\", line 1016, in _bootstrap_inner\n",
            "    self.run()\n",
            "  File \"/usr/lib/python3.10/threading.py\", line 953, in run\n",
            "    self._target(*self._args, **self._kwargs)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/django/utils/autoreload.py\", line 64, in wrapper\n",
            "    fn(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/django/core/management/commands/runserver.py\", line 133, in inner_run\n",
            "    self.check(display_num_errors=True)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/django/core/management/base.py\", line 486, in check\n",
            "    all_issues = checks.run_checks(\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/django/core/checks/registry.py\", line 88, in run_checks\n",
            "    new_errors = check(app_configs=app_configs, databases=databases)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/django/core/checks/urls.py\", line 42, in check_url_namespaces_unique\n",
            "    all_namespaces = _load_all_namespaces(resolver)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/django/core/checks/urls.py\", line 61, in _load_all_namespaces\n",
            "    url_patterns = getattr(resolver, \"url_patterns\", [])\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/django/utils/functional.py\", line 47, in __get__\n",
            "    res = instance.__dict__[self.name] = self.func(instance)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/django/urls/resolvers.py\", line 738, in url_patterns\n",
            "    patterns = getattr(self.urlconf_module, \"urlpatterns\", self.urlconf_module)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/django/utils/functional.py\", line 47, in __get__\n",
            "    res = instance.__dict__[self.name] = self.func(instance)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/django/urls/resolvers.py\", line 731, in urlconf_module\n",
            "    return import_module(self.urlconf_name)\n",
            "  File \"/usr/lib/python3.10/importlib/__init__.py\", line 126, in import_module\n",
            "    return _bootstrap._gcd_import(name[level:], package, level)\n",
            "  File \"<frozen importlib._bootstrap>\", line 1050, in _gcd_import\n",
            "  File \"<frozen importlib._bootstrap>\", line 1027, in _find_and_load\n",
            "  File \"<frozen importlib._bootstrap>\", line 1006, in _find_and_load_unlocked\n",
            "  File \"<frozen importlib._bootstrap>\", line 688, in _load_unlocked\n",
            "  File \"<frozen importlib._bootstrap_external>\", line 883, in exec_module\n",
            "  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\n",
            "  File \"/content/diary_project/diary_project/urls.py\", line 22, in <module>\n",
            "    path('', include('diary.urls')),\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/django/urls/conf.py\", line 39, in include\n",
            "    urlconf_module = import_module(urlconf_module)\n",
            "  File \"/usr/lib/python3.10/importlib/__init__.py\", line 126, in import_module\n",
            "    return _bootstrap._gcd_import(name[level:], package, level)\n",
            "  File \"<frozen importlib._bootstrap>\", line 1050, in _gcd_import\n",
            "  File \"<frozen importlib._bootstrap>\", line 1027, in _find_and_load\n",
            "  File \"<frozen importlib._bootstrap>\", line 1006, in _find_and_load_unlocked\n",
            "  File \"<frozen importlib._bootstrap>\", line 688, in _load_unlocked\n",
            "  File \"<frozen importlib._bootstrap_external>\", line 883, in exec_module\n",
            "  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\n",
            "  File \"/content/diary_project/diary/urls.py\", line 3, in <module>\n",
            "    from . import views\n",
            "  File \"/content/diary_project/diary/views.py\", line 2, in <module>\n",
            "    from .depression_model import depression_predict\n",
            "  File \"/content/diary_project/diary/depression_model.py\", line 69\n",
            "    input_ids = input_ids.long().to(device)\n",
            "    ^\n",
            "IndentationError: expected an indented block after 'for' statement on line 68\n",
            "/content/diary_project/diary/depression_model.py changed, reloading.\n",
            "Watching for file changes with StatReloader\n",
            "Performing system checks...\n",
            "\n",
            "The tokenizer class you load from this checkpoint is not the same type as the class this function is called from. It may result in unexpected tokenization. \n",
            "The tokenizer class you load from this checkpoint is 'XLNetTokenizer'. \n",
            "The class this function is called from is 'KoBERTTokenizer'.\n",
            "System check identified no issues (0 silenced).\n",
            "\u001b[31m\n",
            "You have 18 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): admin, auth, contenttypes, sessions.\u001b[0m\n",
            "\u001b[31mRun 'python manage.py migrate' to apply them.\u001b[0m\n",
            "June 20, 2024 - 14:45:59\n",
            "Django version 5.0.6, using settings 'diary_project.settings'\n",
            "Starting development server at http://127.0.0.1:8000/\n",
            "Quit the server with CONTROL-C.\n",
            "\n",
            "/content/diary_project/diary/depression_model.py changed, reloading.\n",
            "[Kss]: /content/diary_project/diary/depression_model.py changed, reloading.\n",
            "Watching for file changes with StatReloader\n",
            "Performing system checks...\n",
            "\n",
            "The tokenizer class you load from this checkpoint is not the same type as the class this function is called from. It may result in unexpected tokenization. \n",
            "The tokenizer class you load from this checkpoint is 'XLNetTokenizer'. \n",
            "The class this function is called from is 'KoBERTTokenizer'.\n",
            "System check identified no issues (0 silenced).\n",
            "\u001b[31m\n",
            "You have 18 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): admin, auth, contenttypes, sessions.\u001b[0m\n",
            "\u001b[31mRun 'python manage.py migrate' to apply them.\u001b[0m\n",
            "June 20, 2024 - 14:46:32\n",
            "Django version 5.0.6, using settings 'diary_project.settings'\n",
            "Starting development server at http://127.0.0.1:8000/\n",
            "Quit the server with CONTROL-C.\n",
            "\n",
            "/content/diary_project/diary/depression_model.py changed, reloading.\n",
            "[Kss]: /content/diary_project/diary/depression_model.py changed, reloading.\n",
            "Watching for file changes with StatReloader\n",
            "Performing system checks...\n",
            "\n",
            "The tokenizer class you load from this checkpoint is not the same type as the class this function is called from. It may result in unexpected tokenization. \n",
            "The tokenizer class you load from this checkpoint is 'XLNetTokenizer'. \n",
            "The class this function is called from is 'KoBERTTokenizer'.\n",
            "System check identified no issues (0 silenced).\n",
            "\u001b[31m\n",
            "You have 18 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): admin, auth, contenttypes, sessions.\u001b[0m\n",
            "\u001b[31mRun 'python manage.py migrate' to apply them.\u001b[0m\n",
            "June 20, 2024 - 14:47:10\n",
            "Django version 5.0.6, using settings 'diary_project.settings'\n",
            "Starting development server at http://127.0.0.1:8000/\n",
            "Quit the server with CONTROL-C.\n",
            "\n",
            "[20/Jun/2024 14:47:25] \u001b[m\"GET / HTTP/1.1\" 200 472\u001b[0m\n",
            "Not Found: /favicon.ico\n",
            "[Kss]: Not Found: /favicon.ico\n",
            "[20/Jun/2024 14:47:26] \u001b[33m\"GET /favicon.ico HTTP/1.1\" 404 2289\u001b[0m\n",
            "/content/diary_project/diary/depression_model.py changed, reloading.\n",
            "[Kss]: /content/diary_project/diary/depression_model.py changed, reloading.\n",
            "Watching for file changes with StatReloader\n",
            "Performing system checks...\n",
            "\n",
            "The tokenizer class you load from this checkpoint is not the same type as the class this function is called from. It may result in unexpected tokenization. \n",
            "The tokenizer class you load from this checkpoint is 'XLNetTokenizer'. \n",
            "The class this function is called from is 'KoBERTTokenizer'.\n",
            "System check identified no issues (0 silenced).\n",
            "\u001b[31m\n",
            "You have 18 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): admin, auth, contenttypes, sessions.\u001b[0m\n",
            "\u001b[31mRun 'python manage.py migrate' to apply them.\u001b[0m\n",
            "June 20, 2024 - 14:47:46\n",
            "Django version 5.0.6, using settings 'diary_project.settings'\n",
            "Starting development server at http://127.0.0.1:8000/\n",
            "Quit the server with CONTROL-C.\n",
            "\n",
            "/content/diary_project/diary/depression_model.py changed, reloading.\n",
            "[Kss]: /content/diary_project/diary/depression_model.py changed, reloading.\n",
            "Watching for file changes with StatReloader\n",
            "Performing system checks...\n",
            "\n",
            "Exception in thread django-main-thread:\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/lib/python3.10/threading.py\", line 1016, in _bootstrap_inner\n",
            "    self.run()\n",
            "  File \"/usr/lib/python3.10/threading.py\", line 953, in run\n",
            "    self._target(*self._args, **self._kwargs)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/django/utils/autoreload.py\", line 64, in wrapper\n",
            "    fn(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/django/core/management/commands/runserver.py\", line 133, in inner_run\n",
            "    self.check(display_num_errors=True)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/django/core/management/base.py\", line 486, in check\n",
            "    all_issues = checks.run_checks(\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/django/core/checks/registry.py\", line 88, in run_checks\n",
            "    new_errors = check(app_configs=app_configs, databases=databases)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/django/core/checks/urls.py\", line 42, in check_url_namespaces_unique\n",
            "    all_namespaces = _load_all_namespaces(resolver)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/django/core/checks/urls.py\", line 61, in _load_all_namespaces\n",
            "    url_patterns = getattr(resolver, \"url_patterns\", [])\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/django/utils/functional.py\", line 47, in __get__\n",
            "    res = instance.__dict__[self.name] = self.func(instance)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/django/urls/resolvers.py\", line 738, in url_patterns\n",
            "    patterns = getattr(self.urlconf_module, \"urlpatterns\", self.urlconf_module)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/django/utils/functional.py\", line 47, in __get__\n",
            "    res = instance.__dict__[self.name] = self.func(instance)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/django/urls/resolvers.py\", line 731, in urlconf_module\n",
            "    return import_module(self.urlconf_name)\n",
            "  File \"/usr/lib/python3.10/importlib/__init__.py\", line 126, in import_module\n",
            "    return _bootstrap._gcd_import(name[level:], package, level)\n",
            "  File \"<frozen importlib._bootstrap>\", line 1050, in _gcd_import\n",
            "  File \"<frozen importlib._bootstrap>\", line 1027, in _find_and_load\n",
            "  File \"<frozen importlib._bootstrap>\", line 1006, in _find_and_load_unlocked\n",
            "  File \"<frozen importlib._bootstrap>\", line 688, in _load_unlocked\n",
            "  File \"<frozen importlib._bootstrap_external>\", line 883, in exec_module\n",
            "  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\n",
            "  File \"/content/diary_project/diary_project/urls.py\", line 22, in <module>\n",
            "    path('', include('diary.urls')),\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/django/urls/conf.py\", line 39, in include\n",
            "    urlconf_module = import_module(urlconf_module)\n",
            "  File \"/usr/lib/python3.10/importlib/__init__.py\", line 126, in import_module\n",
            "    return _bootstrap._gcd_import(name[level:], package, level)\n",
            "  File \"<frozen importlib._bootstrap>\", line 1050, in _gcd_import\n",
            "  File \"<frozen importlib._bootstrap>\", line 1027, in _find_and_load\n",
            "  File \"<frozen importlib._bootstrap>\", line 1006, in _find_and_load_unlocked\n",
            "  File \"<frozen importlib._bootstrap>\", line 688, in _load_unlocked\n",
            "  File \"<frozen importlib._bootstrap_external>\", line 883, in exec_module\n",
            "  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\n",
            "  File \"/content/diary_project/diary/urls.py\", line 3, in <module>\n",
            "    from . import views\n",
            "  File \"/content/diary_project/diary/views.py\", line 2, in <module>\n",
            "    from .depression_model import depression_predict\n",
            "  File \"/content/diary_project/diary/depression_model.py\", line 68\n",
            "    test_eval = []for batch_id, (input_ids, attention_mask, token_type_ids, label) in enumerate(test_dataloader):\n",
            "                  ^^^\n",
            "SyntaxError: invalid syntax\n",
            "/content/diary_project/diary/depression_model.py changed, reloading.\n",
            "Watching for file changes with StatReloader\n",
            "Performing system checks...\n",
            "\n",
            "Exception in thread django-main-thread:\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/lib/python3.10/threading.py\", line 1016, in _bootstrap_inner\n",
            "    self.run()\n",
            "  File \"/usr/lib/python3.10/threading.py\", line 953, in run\n",
            "    self._target(*self._args, **self._kwargs)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/django/utils/autoreload.py\", line 64, in wrapper\n",
            "    fn(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/django/core/management/commands/runserver.py\", line 133, in inner_run\n",
            "    self.check(display_num_errors=True)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/django/core/management/base.py\", line 486, in check\n",
            "    all_issues = checks.run_checks(\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/django/core/checks/registry.py\", line 88, in run_checks\n",
            "    new_errors = check(app_configs=app_configs, databases=databases)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/django/core/checks/urls.py\", line 42, in check_url_namespaces_unique\n",
            "    all_namespaces = _load_all_namespaces(resolver)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/django/core/checks/urls.py\", line 61, in _load_all_namespaces\n",
            "    url_patterns = getattr(resolver, \"url_patterns\", [])\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/django/utils/functional.py\", line 47, in __get__\n",
            "    res = instance.__dict__[self.name] = self.func(instance)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/django/urls/resolvers.py\", line 738, in url_patterns\n",
            "    patterns = getattr(self.urlconf_module, \"urlpatterns\", self.urlconf_module)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/django/utils/functional.py\", line 47, in __get__\n",
            "    res = instance.__dict__[self.name] = self.func(instance)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/django/urls/resolvers.py\", line 731, in urlconf_module\n",
            "    return import_module(self.urlconf_name)\n",
            "  File \"/usr/lib/python3.10/importlib/__init__.py\", line 126, in import_module\n",
            "    return _bootstrap._gcd_import(name[level:], package, level)\n",
            "  File \"<frozen importlib._bootstrap>\", line 1050, in _gcd_import\n",
            "  File \"<frozen importlib._bootstrap>\", line 1027, in _find_and_load\n",
            "  File \"<frozen importlib._bootstrap>\", line 1006, in _find_and_load_unlocked\n",
            "  File \"<frozen importlib._bootstrap>\", line 688, in _load_unlocked\n",
            "  File \"<frozen importlib._bootstrap_external>\", line 883, in exec_module\n",
            "  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\n",
            "  File \"/content/diary_project/diary_project/urls.py\", line 22, in <module>\n",
            "    path('', include('diary.urls')),\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/django/urls/conf.py\", line 39, in include\n",
            "    urlconf_module = import_module(urlconf_module)\n",
            "  File \"/usr/lib/python3.10/importlib/__init__.py\", line 126, in import_module\n",
            "    return _bootstrap._gcd_import(name[level:], package, level)\n",
            "  File \"<frozen importlib._bootstrap>\", line 1050, in _gcd_import\n",
            "  File \"<frozen importlib._bootstrap>\", line 1027, in _find_and_load\n",
            "  File \"<frozen importlib._bootstrap>\", line 1006, in _find_and_load_unlocked\n",
            "  File \"<frozen importlib._bootstrap>\", line 688, in _load_unlocked\n",
            "  File \"<frozen importlib._bootstrap_external>\", line 883, in exec_module\n",
            "  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\n",
            "  File \"/content/diary_project/diary/urls.py\", line 3, in <module>\n",
            "    from . import views\n",
            "  File \"/content/diary_project/diary/views.py\", line 2, in <module>\n",
            "    from .depression_model import depression_predict\n",
            "  File \"/content/diary_project/diary/depression_model.py\", line 96\n",
            "    return np.argmax(logits)  # 마지막 로짓스 값을 반환할지는 사용 환경에 따라 다를 수 있음\n",
            "    ^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "SyntaxError: 'return' outside function\n",
            "/content/diary_project/diary/depression_model.py changed, reloading.\n",
            "Watching for file changes with StatReloader\n",
            "Performing system checks...\n",
            "\n",
            "The tokenizer class you load from this checkpoint is not the same type as the class this function is called from. It may result in unexpected tokenization. \n",
            "The tokenizer class you load from this checkpoint is 'XLNetTokenizer'. \n",
            "The class this function is called from is 'KoBERTTokenizer'.\n",
            "System check identified no issues (0 silenced).\n",
            "\u001b[31m\n",
            "You have 18 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): admin, auth, contenttypes, sessions.\u001b[0m\n",
            "\u001b[31mRun 'python manage.py migrate' to apply them.\u001b[0m\n",
            "June 20, 2024 - 14:49:20\n",
            "Django version 5.0.6, using settings 'diary_project.settings'\n",
            "Starting development server at http://127.0.0.1:8000/\n",
            "Quit the server with CONTROL-C.\n",
            "\n",
            "[20/Jun/2024 14:49:23] \u001b[m\"GET / HTTP/1.1\" 200 472\u001b[0m\n",
            "Not Found: /favicon.ico\n",
            "[Kss]: Not Found: /favicon.ico\n",
            "[20/Jun/2024 14:49:23] \u001b[33m\"GET /favicon.ico HTTP/1.1\" 404 2289\u001b[0m\n",
            "/content/diary_project/diary/depression_model.py changed, reloading.\n",
            "[Kss]: /content/diary_project/diary/depression_model.py changed, reloading.\n",
            "Watching for file changes with StatReloader\n",
            "Performing system checks...\n",
            "\n",
            "The tokenizer class you load from this checkpoint is not the same type as the class this function is called from. It may result in unexpected tokenization. \n",
            "The tokenizer class you load from this checkpoint is 'XLNetTokenizer'. \n",
            "The class this function is called from is 'KoBERTTokenizer'.\n",
            "System check identified no issues (0 silenced).\n",
            "\u001b[31m\n",
            "You have 18 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): admin, auth, contenttypes, sessions.\u001b[0m\n",
            "\u001b[31mRun 'python manage.py migrate' to apply them.\u001b[0m\n",
            "June 20, 2024 - 14:49:46\n",
            "Django version 5.0.6, using settings 'diary_project.settings'\n",
            "Starting development server at http://127.0.0.1:8000/\n",
            "Quit the server with CONTROL-C.\n",
            "\n",
            "[20/Jun/2024 14:49:50] \u001b[m\"GET / HTTP/1.1\" 200 472\u001b[0m\n",
            "Not Found: /favicon.ico\n",
            "[Kss]: Not Found: /favicon.ico\n",
            "[20/Jun/2024 14:49:50] \u001b[33m\"GET /favicon.ico HTTP/1.1\" 404 2289\u001b[0m\n",
            "[Kss]: Oh! You have mecab in your environment. Kss will take this as a backend! :D\n",
            "\n",
            "너무 우울하다\n",
            ">> 입력하신 내용에서 우울이 느껴집니다.\n",
            "[20/Jun/2024 14:49:59] \u001b[m\"POST / HTTP/1.1\" 200 576\u001b[0m\n",
            "Not Found: /favicon.ico\n",
            "[Kss]: Not Found: /favicon.ico\n",
            "[20/Jun/2024 14:49:59] \u001b[33m\"GET /favicon.ico HTTP/1.1\" 404 2289\u001b[0m\n",
            "/content/diary_project/diary/depression_model.py changed, reloading.\n",
            "[Kss]: /content/diary_project/diary/depression_model.py changed, reloading.\n",
            "Watching for file changes with StatReloader\n",
            "Performing system checks...\n",
            "\n",
            "The tokenizer class you load from this checkpoint is not the same type as the class this function is called from. It may result in unexpected tokenization. \n",
            "The tokenizer class you load from this checkpoint is 'XLNetTokenizer'. \n",
            "The class this function is called from is 'KoBERTTokenizer'.\n",
            "System check identified no issues (0 silenced).\n",
            "\u001b[31m\n",
            "You have 18 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): admin, auth, contenttypes, sessions.\u001b[0m\n",
            "\u001b[31mRun 'python manage.py migrate' to apply them.\u001b[0m\n",
            "June 20, 2024 - 14:50:55\n",
            "Django version 5.0.6, using settings 'diary_project.settings'\n",
            "Starting development server at http://127.0.0.1:8000/\n",
            "Quit the server with CONTROL-C.\n",
            "\n",
            "/content/diary_project/diary/depression_model.py changed, reloading.\n",
            "[Kss]: /content/diary_project/diary/depression_model.py changed, reloading.\n",
            "Watching for file changes with StatReloader\n",
            "Performing system checks...\n",
            "\n",
            "The tokenizer class you load from this checkpoint is not the same type as the class this function is called from. It may result in unexpected tokenization. \n",
            "The tokenizer class you load from this checkpoint is 'XLNetTokenizer'. \n",
            "The class this function is called from is 'KoBERTTokenizer'.\n",
            "System check identified no issues (0 silenced).\n",
            "\u001b[31m\n",
            "You have 18 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): admin, auth, contenttypes, sessions.\u001b[0m\n",
            "\u001b[31mRun 'python manage.py migrate' to apply them.\u001b[0m\n",
            "June 20, 2024 - 14:51:31\n",
            "Django version 5.0.6, using settings 'diary_project.settings'\n",
            "Starting development server at http://127.0.0.1:8000/\n",
            "Quit the server with CONTROL-C.\n",
            "\n",
            "[20/Jun/2024 14:51:36] \u001b[m\"GET / HTTP/1.1\" 200 472\u001b[0m\n",
            "Not Found: /favicon.ico\n",
            "[Kss]: Not Found: /favicon.ico\n",
            "[20/Jun/2024 14:51:36] \u001b[33m\"GET /favicon.ico HTTP/1.1\" 404 2289\u001b[0m\n",
            "/content/diary_project/diary/depression_model.py changed, reloading.\n",
            "[Kss]: /content/diary_project/diary/depression_model.py changed, reloading.\n",
            "Watching for file changes with StatReloader\n",
            "Performing system checks...\n",
            "\n",
            "The tokenizer class you load from this checkpoint is not the same type as the class this function is called from. It may result in unexpected tokenization. \n",
            "The tokenizer class you load from this checkpoint is 'XLNetTokenizer'. \n",
            "The class this function is called from is 'KoBERTTokenizer'.\n",
            "System check identified no issues (0 silenced).\n",
            "\u001b[31m\n",
            "You have 18 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): admin, auth, contenttypes, sessions.\u001b[0m\n",
            "\u001b[31mRun 'python manage.py migrate' to apply them.\u001b[0m\n",
            "June 20, 2024 - 14:51:56\n",
            "Django version 5.0.6, using settings 'diary_project.settings'\n",
            "Starting development server at http://127.0.0.1:8000/\n",
            "Quit the server with CONTROL-C.\n",
            "\n",
            "[Kss]: Oh! You have mecab in your environment. Kss will take this as a backend! :D\n",
            "\n",
            "오늘 기분이 좋았는데 아까 넘어졌어.\n",
            ">> 입력하신 내용에서 우울이 느껴집니다.\n",
            "그래서 갑자기 기분이 안좋아졌어\n",
            ">> 입력하신 내용에서 우울이 느껴집니다.\n",
            "100.0%로 우울합니다.\n",
            "[20/Jun/2024 14:52:00] \u001b[m\"POST / HTTP/1.1\" 200 555\u001b[0m\n",
            "Not Found: /favicon.ico\n",
            "[Kss]: Not Found: /favicon.ico\n",
            "[20/Jun/2024 14:52:00] \u001b[33m\"GET /favicon.ico HTTP/1.1\" 404 2289\u001b[0m\n",
            "오늘 너무 행복했어.\n",
            ">> 입력하신 내용에서 기쁨 혹은 중립이 느껴집니다.\n",
            "완벽한 하루였지\n",
            ">> 입력하신 내용에서 기쁨 혹은 중립이 느껴집니다.\n",
            "근데 보고싶은 사람을 못봤어\n",
            ">> 입력하신 내용에서 우울이 느껴집니다.\n",
            "그게 좀 아쉬워\n",
            ">> 입력하신 내용에서 우울이 느껴집니다.\n",
            "50.0%로 우울합니다.\n",
            "[20/Jun/2024 14:52:53] \u001b[m\"POST / HTTP/1.1\" 200 554\u001b[0m\n",
            "Not Found: /favicon.ico\n",
            "[Kss]: Not Found: /favicon.ico\n",
            "[20/Jun/2024 14:52:53] \u001b[33m\"GET /favicon.ico HTTP/1.1\" 404 2289\u001b[0m\n",
            "나 오늘 너무 우울했어\n",
            ">> 입력하신 내용에서 우울이 느껴집니다.\n",
            "근데 귀여운 강아지를 봐서 기분이 좋아졌어\n",
            "심지어 내가 좋아하는 프로그램도 봐서 행복\n",
            ">> 입력하신 내용에서 기쁨 혹은 중립이 느껴집니다.\n",
            "50.0%로 우울합니다.\n",
            "[20/Jun/2024 14:54:50] \u001b[m\"POST / HTTP/1.1\" 200 554\u001b[0m\n",
            "Not Found: /favicon.ico\n",
            "[Kss]: Not Found: /favicon.ico\n",
            "[20/Jun/2024 14:54:50] \u001b[33m\"GET /favicon.ico HTTP/1.1\" 404 2289\u001b[0m\n",
            "/content/diary_project/diary/depression_model.py changed, reloading.\n",
            "[Kss]: /content/diary_project/diary/depression_model.py changed, reloading.\n",
            "Watching for file changes with StatReloader\n",
            "Performing system checks...\n",
            "\n",
            "The tokenizer class you load from this checkpoint is not the same type as the class this function is called from. It may result in unexpected tokenization. \n",
            "The tokenizer class you load from this checkpoint is 'XLNetTokenizer'. \n",
            "The class this function is called from is 'KoBERTTokenizer'.\n",
            "System check identified no issues (0 silenced).\n",
            "\u001b[31m\n",
            "You have 18 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): admin, auth, contenttypes, sessions.\u001b[0m\n",
            "\u001b[31mRun 'python manage.py migrate' to apply them.\u001b[0m\n",
            "June 20, 2024 - 15:00:24\n",
            "Django version 5.0.6, using settings 'diary_project.settings'\n",
            "Starting development server at http://127.0.0.1:8000/\n",
            "Quit the server with CONTROL-C.\n",
            "\n",
            "[Kss]: Oh! You have mecab in your environment. Kss will take this as a backend! :D\n",
            "\n",
            "나 오늘 너무 우울했어\n",
            ">> 입력하신 내용에서 우울이 느껴집니다.\n",
            "근데 귀여운 강아지를 봐서 기분이 좋아졌어\n",
            "심지어 내가 좋아하는 프로그램도 봐서 행복\n",
            ">> 입력하신 내용에서 기쁨 혹은 중립이 느껴집니다.\n",
            "50.0%로 우울합니다.\n",
            "[20/Jun/2024 15:08:34] \u001b[m\"POST / HTTP/1.1\" 200 2262\u001b[0m\n",
            "Not Found: /favicon.ico\n",
            "[Kss]: Not Found: /favicon.ico\n",
            "[20/Jun/2024 15:08:35] \u001b[33m\"GET /favicon.ico HTTP/1.1\" 404 2289\u001b[0m\n",
            "오늘 너무 행복해\n",
            ">> 입력하신 내용에서 기쁨 혹은 중립이 느껴집니다.\n",
            "0.0%로 우울합니다.\n",
            "[20/Jun/2024 15:08:43] \u001b[m\"POST / HTTP/1.1\" 200 2086\u001b[0m\n",
            "오늘 너무 행복해\n",
            ">> 입력하신 내용에서 기쁨 혹은 중립이 느껴집니다.\n",
            "근데 좀 속상해\n",
            ">> 입력하신 내용에서 우울이 느껴집니다.\n",
            "50.0%로 우울합니다.\n",
            "[20/Jun/2024 15:08:56] \u001b[m\"POST / HTTP/1.1\" 200 2262\u001b[0m\n",
            "오늘 너무 행복해\n",
            "오늘 너무 행복해\n",
            ">> 입력하신 내용에서 기쁨 혹은 중립이 느껴집니다.\n",
            "근데 좀 속상해\n",
            ">> 입력하신 내용에서 기쁨 혹은 중립이 느껴집니다.\n",
            "근데 좀 속상해\n",
            ">> 입력하신 내용에서 우울이 느껴집니다.\n",
            "50.0%로 우울합니다.\n",
            "[20/Jun/2024 15:09:00] \u001b[m\"POST / HTTP/1.1\" 200 2262\u001b[0m\n",
            ">> 입력하신 내용에서 우울이 느껴집니다.\n",
            "50.0%로 우울합니다.\n",
            "[20/Jun/2024 15:09:00] \u001b[m\"POST / HTTP/1.1\" 200 2262\u001b[0m\n",
            "[20/Jun/2024 15:09:14] \u001b[m\"GET / HTTP/1.1\" 200 2086\u001b[0m\n",
            "Not Found: /favicon.ico\n",
            "[Kss]: Not Found: /favicon.ico\n",
            "[20/Jun/2024 15:09:15] \u001b[33m\"GET /favicon.ico HTTP/1.1\" 404 2289\u001b[0m\n",
            "오늘은 행복한 날이야\n",
            ">> 입력하신 내용에서 기쁨 혹은 중립이 느껴집니다.\n",
            "내 생일이었어\n",
            ">> 입력하신 내용에서 우울이 느껴집니다.\n",
            "잠깐 넘어지긴 했지만 그래도 괜찮았어 \n",
            "아빠가 보고싶어\n",
            "그래도 난 씩씩하게 견딜거야\n",
            ">> 입력하신 내용에서 기쁨 혹은 중립이 느껴집니다.\n",
            "33.3%로 우울합니다.\n",
            "[20/Jun/2024 15:09:56] \u001b[m\"POST / HTTP/1.1\" 200 2262\u001b[0m\n",
            "[20/Jun/2024 15:18:59] \u001b[m\"GET / HTTP/1.1\" 200 2151\u001b[0m\n",
            "Not Found: /favicon.ico\n",
            "[Kss]: Not Found: /favicon.ico\n",
            "[20/Jun/2024 15:19:00] \u001b[33m\"GET /favicon.ico HTTP/1.1\" 404 2289\u001b[0m\n",
            "어린왕자라는 노래 영상을 봤다.\n",
            ">> 입력하신 내용에서 놀람이 느껴집니다.\n",
            "가사도 너무 예뻤다.\n",
            ">> 입력하신 내용에서 기쁨 혹은 중립이 느껴집니다.\n",
            "'어린왕자가 내게 말했어 사람이 사람의 마음을 얻는 일이라는게 가장 어렵다고.'라는 가사인데 댓글이 더 아름답게 느껴졌다.\n",
            ">> 입력하신 내용에서 기쁨 혹은 중립이 느껴집니다.\n",
            "나도 그런 사람이 되어야지\n",
            ">> 입력하신 내용에서 기쁨 혹은 중립이 느껴집니다.\n",
            "7.5%로 우울합니다.\n",
            "[20/Jun/2024 15:20:27] \u001b[m\"POST / HTTP/1.1\" 200 2325\u001b[0m\n",
            "어린왕자라는 노래 영상을 봤다.\n",
            ">> 입력하신 내용에서 놀람이 느껴집니다.\n",
            "가사도 너무 예뻤다.\n",
            ">> 입력하신 내용에서 기쁨 혹은 중립이 느껴집니다.\n",
            "'어린왕자가 내게 말했어 사람이 사람의 마음을 얻는 일이라는게 가장 어렵다고.'라는 가사인데 댓글이 더 아름답게 느껴졌다.\n",
            ">> 입력하신 내용에서 기쁨 혹은 중립이 느껴집니다.\n",
            "나도 그런 사람이 되어야지\n",
            ">> 입력하신 내용에서 기쁨 혹은 중립이 느껴집니다.\n",
            "7.5%로 우울합니다.\n",
            "[20/Jun/2024 15:20:51] \u001b[m\"POST / HTTP/1.1\" 200 556\u001b[0m\n",
            "[20/Jun/2024 15:20:53] \u001b[m\"GET / HTTP/1.1\" 200 475\u001b[0m\n",
            "Not Found: /favicon.ico\n",
            "[Kss]: Not Found: /favicon.ico\n",
            "[20/Jun/2024 15:20:54] \u001b[33m\"GET /favicon.ico HTTP/1.1\" 404 2289\u001b[0m\n",
            "어린왕자라는 노래 영상을 봤다.\n",
            ">> 입력하신 내용에서 놀람이 느껴집니다.\n",
            "가사도 너무 예뻤다.\n",
            ">> 입력하신 내용에서 기쁨 혹은 중립이 느껴집니다.\n",
            "'어린왕자가 내게 말했어 사람이 사람의 마음을 얻는 일이라는게 가장 어렵다고.'라는 가사인데 댓글이 더 아름답게 느껴졌다.\n",
            ">> 입력하신 내용에서 기쁨 혹은 중립이 느껴집니다.\n",
            "나도 그런 사람이 되어야지\n",
            ">> 입력하신 내용에서 기쁨 혹은 중립이 느껴집니다.\n",
            "7.5%로 우울합니다.\n",
            "[20/Jun/2024 15:20:57] \u001b[m\"POST / HTTP/1.1\" 200 556\u001b[0m\n",
            "Not Found: /favicon.ico\n",
            "[Kss]: Not Found: /favicon.ico\n",
            "[20/Jun/2024 15:20:58] \u001b[33m\"GET /favicon.ico HTTP/1.1\" 404 2289\u001b[0m\n",
            "[20/Jun/2024 15:38:22] \u001b[m\"GET / HTTP/1.1\" 200 1185\u001b[0m\n",
            "Not Found: /favicon.ico\n",
            "[Kss]: Not Found: /favicon.ico\n",
            "[20/Jun/2024 15:38:23] \u001b[33m\"GET /favicon.ico HTTP/1.1\" 404 2289\u001b[0m\n",
            "[20/Jun/2024 15:39:15] \u001b[m\"GET / HTTP/1.1\" 200 1200\u001b[0m\n",
            "Not Found: /favicon.ico\n",
            "[Kss]: Not Found: /favicon.ico\n",
            "[20/Jun/2024 15:39:15] \u001b[33m\"GET /favicon.ico HTTP/1.1\" 404 2289\u001b[0m\n",
            "[20/Jun/2024 15:42:36] \u001b[m\"GET / HTTP/1.1\" 200 495\u001b[0m\n",
            "Not Found: /favicon.ico\n",
            "[Kss]: Not Found: /favicon.ico\n",
            "[20/Jun/2024 15:42:36] \u001b[33m\"GET /favicon.ico HTTP/1.1\" 404 2289\u001b[0m\n",
            "[20/Jun/2024 15:42:54] \u001b[m\"GET / HTTP/1.1\" 200 495\u001b[0m\n",
            "Not Found: /favicon.ico\n",
            "[Kss]: Not Found: /favicon.ico\n",
            "[20/Jun/2024 15:42:54] \u001b[33m\"GET /favicon.ico HTTP/1.1\" 404 2289\u001b[0m\n",
            "[20/Jun/2024 15:43:05] \u001b[m\"GET / HTTP/1.1\" 200 495\u001b[0m\n",
            "Not Found: /favicon.ico\n",
            "[Kss]: Not Found: /favicon.ico\n",
            "[20/Jun/2024 15:43:06] \u001b[33m\"GET /favicon.ico HTTP/1.1\" 404 2289\u001b[0m\n",
            "[20/Jun/2024 15:43:24] \u001b[m\"GET / HTTP/1.1\" 200 494\u001b[0m\n",
            "Not Found: /favicon.ico\n",
            "[Kss]: Not Found: /favicon.ico\n",
            "[20/Jun/2024 15:43:25] \u001b[33m\"GET /favicon.ico HTTP/1.1\" 404 2289\u001b[0m\n",
            "[20/Jun/2024 15:43:25] \u001b[m\"GET / HTTP/1.1\" 200 494\u001b[0m\n",
            "Not Found: /favicon.ico\n",
            "[Kss]: Not Found: /favicon.ico\n",
            "[20/Jun/2024 15:43:26] \u001b[33m\"GET /favicon.ico HTTP/1.1\" 404 2289\u001b[0m\n",
            "[20/Jun/2024 15:43:26] \u001b[m\"GET / HTTP/1.1\" 200 494\u001b[0m\n",
            "Not Found: /favicon.ico\n",
            "[Kss]: Not Found: /favicon.ico\n",
            "[20/Jun/2024 15:43:26] \u001b[33m\"GET /favicon.ico HTTP/1.1\" 404 2289\u001b[0m\n",
            "[20/Jun/2024 15:43:36] \u001b[m\"GET / HTTP/1.1\" 200 494\u001b[0m\n",
            "Not Found: /favicon.ico\n",
            "[Kss]: Not Found: /favicon.ico\n",
            "[20/Jun/2024 15:43:36] \u001b[33m\"GET /favicon.ico HTTP/1.1\" 404 2289\u001b[0m\n",
            "[20/Jun/2024 15:43:51] \u001b[m\"GET / HTTP/1.1\" 200 494\u001b[0m\n",
            "Not Found: /favicon.ico\n",
            "[Kss]: Not Found: /favicon.ico\n",
            "[20/Jun/2024 15:43:52] \u001b[33m\"GET /favicon.ico HTTP/1.1\" 404 2289\u001b[0m\n",
            "[20/Jun/2024 15:43:53] \u001b[m\"GET / HTTP/1.1\" 200 494\u001b[0m\n",
            "Not Found: /favicon.ico\n",
            "[Kss]: Not Found: /favicon.ico\n",
            "[20/Jun/2024 15:43:53] \u001b[33m\"GET /favicon.ico HTTP/1.1\" 404 2289\u001b[0m\n",
            "[20/Jun/2024 15:44:01] \u001b[m\"GET / HTTP/1.1\" 200 494\u001b[0m\n",
            "Not Found: /favicon.ico\n",
            "[Kss]: Not Found: /favicon.ico\n",
            "[20/Jun/2024 15:44:01] \u001b[33m\"GET /favicon.ico HTTP/1.1\" 404 2289\u001b[0m\n",
            "[20/Jun/2024 15:44:09] \u001b[m\"GET / HTTP/1.1\" 200 495\u001b[0m\n",
            "Not Found: /favicon.ico\n",
            "[Kss]: Not Found: /favicon.ico\n",
            "[20/Jun/2024 15:44:10] \u001b[33m\"GET /favicon.ico HTTP/1.1\" 404 2289\u001b[0m\n",
            "[20/Jun/2024 15:44:19] \u001b[m\"GET / HTTP/1.1\" 200 495\u001b[0m\n",
            "Not Found: /favicon.ico\n",
            "[Kss]: Not Found: /favicon.ico\n",
            "[20/Jun/2024 15:44:19] \u001b[33m\"GET /favicon.ico HTTP/1.1\" 404 2289\u001b[0m\n",
            "[20/Jun/2024 15:44:20] \u001b[m\"GET / HTTP/1.1\" 200 494\u001b[0m\n",
            "Not Found: /favicon.ico\n",
            "[Kss]: Not Found: /favicon.ico\n",
            "[20/Jun/2024 15:44:20] \u001b[33m\"GET /favicon.ico HTTP/1.1\" 404 2289\u001b[0m\n",
            "[20/Jun/2024 15:44:27] \u001b[m\"GET / HTTP/1.1\" 200 494\u001b[0m\n",
            "Not Found: /favicon.ico\n",
            "[Kss]: Not Found: /favicon.ico\n",
            "[20/Jun/2024 15:44:28] \u001b[33m\"GET /favicon.ico HTTP/1.1\" 404 2289\u001b[0m\n",
            "[20/Jun/2024 15:44:48] \u001b[m\"GET / HTTP/1.1\" 200 494\u001b[0m\n",
            "Not Found: /favicon.ico\n",
            "[Kss]: Not Found: /favicon.ico\n",
            "[20/Jun/2024 15:44:49] \u001b[33m\"GET /favicon.ico HTTP/1.1\" 404 2289\u001b[0m\n",
            "[20/Jun/2024 15:45:05] \u001b[m\"GET / HTTP/1.1\" 200 494\u001b[0m\n",
            "Not Found: /favicon.ico\n",
            "[Kss]: Not Found: /favicon.ico\n",
            "[20/Jun/2024 15:45:06] \u001b[33m\"GET /favicon.ico HTTP/1.1\" 404 2289\u001b[0m\n",
            "[20/Jun/2024 15:46:08] \u001b[m\"GET / HTTP/1.1\" 200 494\u001b[0m\n",
            "Not Found: /favicon.ico\n",
            "[Kss]: Not Found: /favicon.ico\n",
            "[20/Jun/2024 15:46:09] \u001b[33m\"GET /favicon.ico HTTP/1.1\" 404 2289\u001b[0m\n",
            "[20/Jun/2024 15:46:35] \u001b[m\"GET / HTTP/1.1\" 200 493\u001b[0m\n",
            "Not Found: /favicon.ico\n",
            "[Kss]: Not Found: /favicon.ico\n",
            "[20/Jun/2024 15:46:35] \u001b[33m\"GET /favicon.ico HTTP/1.1\" 404 2289\u001b[0m\n",
            "[20/Jun/2024 15:46:36] \u001b[m\"GET / HTTP/1.1\" 200 493\u001b[0m\n",
            "Not Found: /favicon.ico\n",
            "[Kss]: Not Found: /favicon.ico\n",
            "[20/Jun/2024 15:46:36] \u001b[33m\"GET /favicon.ico HTTP/1.1\" 404 2289\u001b[0m\n",
            "어린왕자라는 노래 영상을 봤다.\n",
            ">> 입력하신 내용에서 놀람이 느껴집니다.\n",
            "가사도 너무 예뻤다.\n",
            ">> 입력하신 내용에서 기쁨 혹은 중립이 느껴집니다.\n",
            "'어린왕자가 내게 말했어 사람이 사람의 마음을 얻는 일이라는게 가장 어렵다고.'라는 가사인데 댓글이 더 아름답게 느껴졌다.\n",
            ">> 입력하신 내용에서 기쁨 혹은 중립이 느껴집니다.\n",
            "나도 그런 사람이 되어야지\n",
            ">> 입력하신 내용에서 기쁨 혹은 중립이 느껴집니다.\n",
            "7.5%로 우울합니다.\n",
            "[20/Jun/2024 15:46:48] \u001b[m\"POST / HTTP/1.1\" 200 589\u001b[0m\n",
            "Not Found: /favicon.ico\n",
            "[Kss]: Not Found: /favicon.ico\n",
            "[20/Jun/2024 15:46:49] \u001b[33m\"GET /favicon.ico HTTP/1.1\" 404 2289\u001b[0m\n",
            "어린왕자라는 노래 영상을 봤다.\n",
            ">> 입력하신 내용에서 놀람이 느껴집니다.\n",
            "가사도 너무 예뻤다.\n",
            ">> 입력하신 내용에서 기쁨 혹은 중립이 느껴집니다.\n",
            "'어린왕자가 내게 말했어 사람이 사람의 마음을 얻는 일이라는게 가장 어렵다고.'라는 가사인데 댓글이 더 아름답게 느껴졌다.\n",
            ">> 입력하신 내용에서 기쁨 혹은 중립이 느껴집니다.\n",
            "나도 그런 사람이 되어야지\n",
            ">> 입력하신 내용에서 기쁨 혹은 중립이 느껴집니다.\n",
            "7.5%로 우울합니다.\n",
            "[20/Jun/2024 15:52:00] \u001b[m\"POST / HTTP/1.1\" 200 726\u001b[0m\n",
            "Not Found: /favicon.ico\n",
            "[Kss]: Not Found: /favicon.ico\n",
            "[20/Jun/2024 15:52:01] \u001b[33m\"GET /favicon.ico HTTP/1.1\" 404 2289\u001b[0m\n",
            "어린왕자라는 노래 영상을 봤다.\n",
            ">> 입력하신 내용에서 놀람이 느껴집니다.\n",
            "가사도 너무 예뻤다.\n",
            ">> 입력하신 내용에서 기쁨 혹은 중립이 느껴집니다.\n",
            "'어린왕자가 내게 말했어 사람이 사람의 마음을 얻는 일이라는게 가장 어렵다고.'라는 가사인데 댓글이 더 아름답게 느껴졌다.\n",
            ">> 입력하신 내용에서 기쁨 혹은 중립이 느껴집니다.\n",
            "나도 그런 사람이 되어야지\n",
            ">> 입력하신 내용에서 기쁨 혹은 중립이 느껴집니다.\n",
            "7.5%로 우울합니다.\n",
            "[20/Jun/2024 15:52:46] \u001b[m\"POST / HTTP/1.1\" 200 727\u001b[0m\n",
            "Not Found: /favicon.ico\n",
            "[Kss]: Not Found: /favicon.ico\n",
            "[20/Jun/2024 15:52:47] \u001b[33m\"GET /favicon.ico HTTP/1.1\" 404 2289\u001b[0m\n",
            "어린왕자라는 노래 영상을 봤다.\n",
            ">> 입력하신 내용에서 놀람이 느껴집니다.\n",
            "가사도 너무 예뻤다.\n",
            ">> 입력하신 내용에서 기쁨 혹은 중립이 느껴집니다.\n",
            "'어린왕자가 내게 말했어 사람이 사람의 마음을 얻는 일이라는게 가장 어렵다고.'라는 가사인데 댓글이 더 아름답게 느껴졌다.\n",
            ">> 입력하신 내용에서 기쁨 혹은 중립이 느껴집니다.\n",
            "나도 그런 사람이 되어야지\n",
            ">> 입력하신 내용에서 기쁨 혹은 중립이 느껴집니다.\n",
            "7.5%로 우울합니다.\n",
            "[20/Jun/2024 15:53:35] \u001b[m\"POST / HTTP/1.1\" 200 717\u001b[0m\n",
            "Not Found: /favicon.ico\n",
            "[Kss]: Not Found: /favicon.ico\n",
            "[20/Jun/2024 15:53:36] \u001b[33m\"GET /favicon.ico HTTP/1.1\" 404 2289\u001b[0m\n",
            "[20/Jun/2024 15:53:48] \u001b[m\"GET / HTTP/1.1\" 200 630\u001b[0m\n",
            "Not Found: /favicon.ico\n",
            "[Kss]: Not Found: /favicon.ico\n",
            "[20/Jun/2024 15:53:49] \u001b[33m\"GET /favicon.ico HTTP/1.1\" 404 2289\u001b[0m\n",
            "[20/Jun/2024 15:54:35] \u001b[m\"GET / HTTP/1.1\" 200 644\u001b[0m\n",
            "Not Found: /favicon.ico\n",
            "[Kss]: Not Found: /favicon.ico\n",
            "[20/Jun/2024 15:54:36] \u001b[33m\"GET /favicon.ico HTTP/1.1\" 404 2289\u001b[0m\n",
            "[20/Jun/2024 15:55:12] \u001b[m\"GET / HTTP/1.1\" 200 644\u001b[0m\n",
            "Not Found: /favicon.ico\n",
            "[Kss]: Not Found: /favicon.ico\n",
            "[20/Jun/2024 15:55:12] \u001b[33m\"GET /favicon.ico HTTP/1.1\" 404 2289\u001b[0m\n",
            "사랑해\n",
            ">> 입력하신 내용에서 기쁨 혹은 중립이 느껴집니다.\n",
            "0.0%로 우울합니다.\n",
            "[20/Jun/2024 15:55:22] \u001b[m\"POST / HTTP/1.1\" 200 644\u001b[0m\n",
            "Not Found: /favicon.ico\n",
            "[Kss]: Not Found: /favicon.ico\n",
            "[20/Jun/2024 15:55:23] \u001b[33m\"GET /favicon.ico HTTP/1.1\" 404 2289\u001b[0m\n",
            "사랑해\n",
            ">> 입력하신 내용에서 기쁨 혹은 중립이 느껴집니다.\n",
            "0.0%로 우울합니다.\n",
            "[20/Jun/2024 15:55:52] \u001b[m\"POST / HTTP/1.1\" 200 630\u001b[0m\n",
            "Not Found: /favicon.ico\n",
            "[Kss]: Not Found: /favicon.ico\n",
            "[20/Jun/2024 15:55:52] \u001b[33m\"GET /favicon.ico HTTP/1.1\" 404 2289\u001b[0m\n",
            "사랑해\n",
            ">> 입력하신 내용에서 기쁨 혹은 중립이 느껴집니다.\n",
            "0.0%로 우울합니다.\n",
            "[20/Jun/2024 15:55:58] \u001b[m\"POST / HTTP/1.1\" 200 630\u001b[0m\n",
            "Not Found: /favicon.ico\n",
            "[Kss]: Not Found: /favicon.ico\n",
            "[20/Jun/2024 15:55:59] \u001b[33m\"GET /favicon.ico HTTP/1.1\" 404 2289\u001b[0m\n",
            "사랑해\n",
            ">> 입력하신 내용에서 기쁨 혹은 중립이 느껴집니다.\n",
            "0.0%로 우울합니다.\n",
            "[20/Jun/2024 15:56:12] \u001b[m\"POST / HTTP/1.1\" 200 630\u001b[0m\n",
            "Not Found: /favicon.ico\n",
            "[Kss]: Not Found: /favicon.ico\n",
            "[20/Jun/2024 15:56:12] \u001b[33m\"GET /favicon.ico HTTP/1.1\" 404 2289\u001b[0m\n",
            "[20/Jun/2024 15:56:21] \u001b[m\"GET / HTTP/1.1\" 200 630\u001b[0m\n",
            "Not Found: /favicon.ico\n",
            "[Kss]: Not Found: /favicon.ico\n",
            "[20/Jun/2024 15:56:22] \u001b[33m\"GET /favicon.ico HTTP/1.1\" 404 2289\u001b[0m\n",
            "사랑해\n",
            ">> 입력하신 내용에서 기쁨 혹은 중립이 느껴집니다.\n",
            "0.0%로 우울합니다.\n",
            "[20/Jun/2024 15:56:25] \u001b[m\"POST / HTTP/1.1\" 200 630\u001b[0m\n",
            "Not Found: /favicon.ico\n",
            "[Kss]: Not Found: /favicon.ico\n",
            "[20/Jun/2024 15:56:25] \u001b[33m\"GET /favicon.ico HTTP/1.1\" 404 2289\u001b[0m\n",
            "[20/Jun/2024 15:56:52] \u001b[m\"GET / HTTP/1.1\" 200 493\u001b[0m\n",
            "Not Found: /favicon.ico\n",
            "[Kss]: Not Found: /favicon.ico\n",
            "[20/Jun/2024 15:56:52] \u001b[33m\"GET /favicon.ico HTTP/1.1\" 404 2289\u001b[0m\n",
            "사랑해\n",
            ">> 입력하신 내용에서 기쁨 혹은 중립이 느껴집니다.\n",
            "0.0%로 우울합니다.\n",
            "[20/Jun/2024 15:56:57] \u001b[m\"POST / HTTP/1.1\" 200 493\u001b[0m\n",
            "Not Found: /favicon.ico\n",
            "[Kss]: Not Found: /favicon.ico\n",
            "[20/Jun/2024 15:56:57] \u001b[33m\"GET /favicon.ico HTTP/1.1\" 404 2289\u001b[0m\n",
            "[20/Jun/2024 15:57:39] \u001b[m\"GET / HTTP/1.1\" 200 493\u001b[0m\n",
            "Not Found: /favicon.ico\n",
            "[Kss]: Not Found: /favicon.ico\n",
            "[20/Jun/2024 15:57:39] \u001b[33m\"GET /favicon.ico HTTP/1.1\" 404 2289\u001b[0m\n",
            "어린왕자라는 노래 영상을 봤다.\n",
            ">> 입력하신 내용에서 놀람이 느껴집니다.\n",
            "가사도 너무 예뻤다.\n",
            ">> 입력하신 내용에서 기쁨 혹은 중립이 느껴집니다.\n",
            "'어린왕자가 내게 말했어 사람이 사람의 마음을 얻는 일이라는게 가장 어렵다고.'라는 가사인데 댓글이 더 아름답게 느껴졌다.\n",
            ">> 입력하신 내용에서 기쁨 혹은 중립이 느껴집니다.\n",
            "나도 그런 사람이 되어야지\n",
            ">> 입력하신 내용에서 기쁨 혹은 중립이 느껴집니다.\n",
            "7.5%로 우울합니다.\n",
            "[20/Jun/2024 15:57:46] \u001b[m\"POST / HTTP/1.1\" 200 589\u001b[0m\n",
            "Not Found: /favicon.ico\n",
            "[Kss]: Not Found: /favicon.ico\n",
            "[20/Jun/2024 15:57:46] \u001b[33m\"GET /favicon.ico HTTP/1.1\" 404 2289\u001b[0m\n",
            "[20/Jun/2024 15:59:36] \u001b[m\"GET / HTTP/1.1\" 200 1507\u001b[0m\n",
            "Not Found: /favicon.ico\n",
            "[Kss]: Not Found: /favicon.ico\n",
            "[20/Jun/2024 15:59:36] \u001b[33m\"GET /favicon.ico HTTP/1.1\" 404 2289\u001b[0m\n",
            "[20/Jun/2024 16:00:33] \u001b[m\"GET / HTTP/1.1\" 200 689\u001b[0m\n",
            "Not Found: /favicon.ico\n",
            "[Kss]: Not Found: /favicon.ico\n",
            "[20/Jun/2024 16:00:33] \u001b[33m\"GET /favicon.ico HTTP/1.1\" 404 2289\u001b[0m\n",
            "사랑해\n",
            ">> 입력하신 내용에서 기쁨 혹은 중립이 느껴집니다.\n",
            "0.0%로 우울합니다.\n",
            "[20/Jun/2024 16:00:38] \u001b[m\"POST / HTTP/1.1\" 200 689\u001b[0m\n",
            "Not Found: /favicon.ico\n",
            "[Kss]: Not Found: /favicon.ico\n",
            "[20/Jun/2024 16:00:39] \u001b[33m\"GET /favicon.ico HTTP/1.1\" 404 2289\u001b[0m\n",
            "사랑해\n",
            ">> 입력하신 내용에서 기쁨 혹은 중립이 느껴집니다.\n",
            "0.0%로 우울합니다.\n",
            "[20/Jun/2024 16:02:43] \u001b[m\"POST / HTTP/1.1\" 200 589\u001b[0m\n",
            "Not Found: /favicon.ico\n",
            "[Kss]: Not Found: /favicon.ico\n",
            "[20/Jun/2024 16:02:43] \u001b[33m\"GET /favicon.ico HTTP/1.1\" 404 2289\u001b[0m\n",
            "슬퍼\n",
            ">> 입력하신 내용에서 우울이 느껴집니다.\n",
            "100.0%로 우울합니다.\n",
            "[20/Jun/2024 16:02:50] \u001b[m\"POST / HTTP/1.1\" 200 591\u001b[0m\n",
            "Not Found: /favicon.ico\n",
            "[Kss]: Not Found: /favicon.ico\n",
            "[20/Jun/2024 16:02:50] \u001b[33m\"GET /favicon.ico HTTP/1.1\" 404 2289\u001b[0m\n",
            "사랑해\n",
            ">> 입력하신 내용에서 기쁨 혹은 중립이 느껴집니다.\n",
            "0.0%로 우울합니다.\n",
            "[20/Jun/2024 16:02:55] \u001b[m\"POST / HTTP/1.1\" 200 589\u001b[0m\n",
            "Not Found: /favicon.ico\n",
            "[Kss]: Not Found: /favicon.ico\n",
            "[20/Jun/2024 16:02:55] \u001b[33m\"GET /favicon.ico HTTP/1.1\" 404 2289\u001b[0m\n",
            "사랑해\n",
            ">> 입력하신 내용에서 기쁨 혹은 중립이 느껴집니다.\n",
            "0.0%로 우울합니다.\n",
            "[20/Jun/2024 16:05:37] \u001b[m\"POST / HTTP/1.1\" 200 1275\u001b[0m\n",
            "Not Found: /favicon.ico\n",
            "[Kss]: Not Found: /favicon.ico\n",
            "[20/Jun/2024 16:05:37] \u001b[33m\"GET /favicon.ico HTTP/1.1\" 404 2289\u001b[0m\n",
            "사랑해\n",
            ">> 입력하신 내용에서 기쁨 혹은 중립이 느껴집니다.\n",
            "0.0%로 우울합니다.\n",
            "[20/Jun/2024 16:05:42] \u001b[m\"POST / HTTP/1.1\" 200 1275\u001b[0m\n",
            "Not Found: /favicon.ico\n",
            "[Kss]: Not Found: /favicon.ico\n",
            "[20/Jun/2024 16:05:43] \u001b[33m\"GET /favicon.ico HTTP/1.1\" 404 2289\u001b[0m\n",
            "사랑해\n",
            ">> 입력하신 내용에서 기쁨 혹은 중립이 느껴집니다.\n",
            "0.0%로 우울합니다.\n",
            "[20/Jun/2024 16:07:00] \u001b[m\"POST / HTTP/1.1\" 200 1279\u001b[0m\n",
            "Not Found: /favicon.ico\n",
            "[Kss]: Not Found: /favicon.ico\n",
            "[20/Jun/2024 16:07:00] \u001b[33m\"GET /favicon.ico HTTP/1.1\" 404 2289\u001b[0m\n",
            "싫어\n",
            ">> 입력하신 내용에서 우울이 느껴집니다.\n",
            "100.0%로 우울합니다.\n",
            "[20/Jun/2024 16:07:05] \u001b[m\"POST / HTTP/1.1\" 200 1281\u001b[0m\n",
            "Not Found: /favicon.ico\n",
            "[Kss]: Not Found: /favicon.ico\n",
            "[20/Jun/2024 16:07:06] \u001b[33m\"GET /favicon.ico HTTP/1.1\" 404 2289\u001b[0m\n",
            "[20/Jun/2024 16:08:22] \u001b[m\"GET / HTTP/1.1\" 200 1185\u001b[0m\n",
            "Not Found: /favicon.ico\n",
            "[Kss]: Not Found: /favicon.ico\n",
            "[20/Jun/2024 16:08:23] \u001b[33m\"GET /favicon.ico HTTP/1.1\" 404 2289\u001b[0m\n",
            "사랑해\n",
            ">> 입력하신 내용에서 기쁨 혹은 중립이 느껴집니다.\n",
            "0.0%로 우울합니다.\n",
            "[20/Jun/2024 16:08:26] \u001b[m\"POST / HTTP/1.1\" 200 1282\u001b[0m\n",
            "사랑해\n",
            ">> 입력하신 내용에서 기쁨 혹은 중립이 느껴집니다.\n",
            "0.0%로 우울합니다.\n",
            "[20/Jun/2024 16:08:27] \u001b[m\"POST / HTTP/1.1\" 200 1282\u001b[0m\n",
            "Not Found: /favicon.ico\n",
            "[Kss]: Not Found: /favicon.ico\n",
            "[20/Jun/2024 16:08:28] \u001b[33m\"GET /favicon.ico HTTP/1.1\" 404 2289\u001b[0m\n",
            "안사랑해\n",
            ">> 입력하신 내용에서 기쁨 혹은 중립이 느껴집니다.\n",
            "0.0%로 우울합니다.\n",
            "[20/Jun/2024 16:08:34] \u001b[m\"POST / HTTP/1.1\" 200 1282\u001b[0m\n",
            "Not Found: /favicon.ico\n",
            "[Kss]: Not Found: /favicon.ico\n",
            "[20/Jun/2024 16:08:35] \u001b[33m\"GET /favicon.ico HTTP/1.1\" 404 2289\u001b[0m\n",
            "[20/Jun/2024 16:08:50] \u001b[m\"GET / HTTP/1.1\" 200 1185\u001b[0m\n",
            "Not Found: /favicon.ico\n",
            "[Kss]: Not Found: /favicon.ico\n",
            "[20/Jun/2024 16:08:51] \u001b[33m\"GET /favicon.ico HTTP/1.1\" 404 2289\u001b[0m\n",
            "사랑해\n",
            ">> 입력하신 내용에서 기쁨 혹은 중립이 느껴집니다.\n",
            "0.0%로 우울합니다.\n",
            "[20/Jun/2024 16:08:55] \u001b[m\"POST / HTTP/1.1\" 200 1282\u001b[0m\n",
            "Not Found: /favicon.ico\n",
            "[Kss]: Not Found: /favicon.ico\n",
            "[20/Jun/2024 16:08:56] \u001b[33m\"GET /favicon.ico HTTP/1.1\" 404 2289\u001b[0m\n",
            "[20/Jun/2024 16:15:15] \u001b[m\"GET / HTTP/1.1\" 200 678\u001b[0m\n",
            "Not Found: /favicon.ico\n",
            "[Kss]: Not Found: /favicon.ico\n",
            "[20/Jun/2024 16:15:16] \u001b[33m\"GET /favicon.ico HTTP/1.1\" 404 2289\u001b[0m\n",
            "[20/Jun/2024 16:16:57] \u001b[m\"GET / HTTP/1.1\" 200 684\u001b[0m\n",
            "Not Found: /favicon.ico\n",
            "[Kss]: Not Found: /favicon.ico\n",
            "[20/Jun/2024 16:16:57] \u001b[33m\"GET /favicon.ico HTTP/1.1\" 404 2289\u001b[0m\n",
            "[20/Jun/2024 16:17:12] \u001b[m\"GET / HTTP/1.1\" 200 684\u001b[0m\n",
            "Not Found: /favicon.ico\n",
            "[Kss]: Not Found: /favicon.ico\n",
            "[20/Jun/2024 16:17:12] \u001b[33m\"GET /favicon.ico HTTP/1.1\" 404 2289\u001b[0m\n",
            "[20/Jun/2024 16:17:20] \u001b[m\"GET / HTTP/1.1\" 200 684\u001b[0m\n",
            "Not Found: /favicon.ico\n",
            "[Kss]: Not Found: /favicon.ico\n",
            "[20/Jun/2024 16:17:20] \u001b[33m\"GET /favicon.ico HTTP/1.1\" 404 2289\u001b[0m\n",
            "[20/Jun/2024 16:17:33] \u001b[m\"GET / HTTP/1.1\" 200 519\u001b[0m\n",
            "Not Found: /favicon.ico\n",
            "[Kss]: Not Found: /favicon.ico\n",
            "[20/Jun/2024 16:17:33] \u001b[33m\"GET /favicon.ico HTTP/1.1\" 404 2289\u001b[0m\n",
            "사랑해\n",
            ">> 입력하신 내용에서 기쁨 혹은 중립이 느껴집니다.\n",
            "0.0%로 우울합니다.\n",
            "[20/Jun/2024 16:17:36] \u001b[m\"POST / HTTP/1.1\" 200 611\u001b[0m\n",
            "사랑해\n",
            "사랑해\n",
            "사랑해\n",
            ">> 입력하신 내용에서 기쁨 혹은 중립이 느껴집니다.\n",
            "0.0%로 우울합니다.\n",
            "[20/Jun/2024 16:17:37] \u001b[m\"POST / HTTP/1.1\" 200 611\u001b[0m\n",
            ">> 입력하신 내용에서 기쁨 혹은 중립이 느껴집니다.\n",
            "0.0%로 우울합니다.\n",
            "[20/Jun/2024 16:17:37] \u001b[m\"POST / HTTP/1.1\" 200 611\u001b[0m\n",
            ">> 입력하신 내용에서 기쁨 혹은 중립이 느껴집니다.\n",
            "0.0%로 우울합니다.\n",
            "[20/Jun/2024 16:17:37] \u001b[m\"POST / HTTP/1.1\" 200 611\u001b[0m\n",
            "Not Found: /favicon.ico\n",
            "[Kss]: Not Found: /favicon.ico\n",
            "[20/Jun/2024 16:17:38] \u001b[33m\"GET /favicon.ico HTTP/1.1\" 404 2289\u001b[0m\n",
            "사랑해\n",
            ">> 입력하신 내용에서 기쁨 혹은 중립이 느껴집니다.\n",
            "0.0%로 우울합니다.\n",
            "[20/Jun/2024 16:17:45] \u001b[m\"POST / HTTP/1.1\" 200 776\u001b[0m\n",
            "Not Found: /favicon.ico\n",
            "[Kss]: Not Found: /favicon.ico\n",
            "[20/Jun/2024 16:17:45] \u001b[33m\"GET /favicon.ico HTTP/1.1\" 404 2289\u001b[0m\n",
            "사랑해\n",
            ">> 입력하신 내용에서 기쁨 혹은 중립이 느껴집니다.\n",
            "0.0%로 우울합니다.\n",
            "[20/Jun/2024 16:18:04] \u001b[m\"POST / HTTP/1.1\" 200 611\u001b[0m\n",
            "Not Found: /favicon.ico\n",
            "[Kss]: Not Found: /favicon.ico\n",
            "[20/Jun/2024 16:18:04] \u001b[33m\"GET /favicon.ico HTTP/1.1\" 404 2289\u001b[0m\n",
            "[20/Jun/2024 16:18:05] \u001b[m\"POST / HTTP/1.1\" 200 514\u001b[0m\n",
            "Not Found: /favicon.ico\n",
            "[Kss]: Not Found: /favicon.ico\n",
            "[20/Jun/2024 16:18:05] \u001b[33m\"GET /favicon.ico HTTP/1.1\" 404 2289\u001b[0m\n",
            "싫어\n",
            ">> 입력하신 내용에서 우울이 느껴집니다.\n",
            "100.0%로 우울합니다.\n",
            "[20/Jun/2024 16:18:10] \u001b[m\"POST / HTTP/1.1\" 200 613\u001b[0m\n",
            "Not Found: /favicon.ico\n",
            "[Kss]: Not Found: /favicon.ico\n",
            "[20/Jun/2024 16:18:10] \u001b[33m\"GET /favicon.ico HTTP/1.1\" 404 2289\u001b[0m\n",
            "사랑해\n",
            ">> 입력하신 내용에서 기쁨 혹은 중립이 느껴집니다.\n",
            "0.0%로 우울합니다.\n",
            "[20/Jun/2024 16:18:15] \u001b[m\"POST / HTTP/1.1\" 200 611\u001b[0m\n",
            "Not Found: /favicon.ico\n",
            "[Kss]: Not Found: /favicon.ico\n",
            "[20/Jun/2024 16:18:16] \u001b[33m\"GET /favicon.ico HTTP/1.1\" 404 2289\u001b[0m\n",
            "[20/Jun/2024 16:20:04] \u001b[m\"GET / HTTP/1.1\" 200 514\u001b[0m\n",
            "Not Found: /favicon.ico\n",
            "[Kss]: Not Found: /favicon.ico\n",
            "[20/Jun/2024 16:20:05] \u001b[33m\"GET /favicon.ico HTTP/1.1\" 404 2289\u001b[0m\n",
            "좋아요\n",
            ">> 입력하신 내용에서 기쁨 혹은 중립이 느껴집니다.\n",
            "0.0%로 우울합니다.\n",
            "[20/Jun/2024 16:20:09] \u001b[m\"POST / HTTP/1.1\" 200 611\u001b[0m\n",
            "Not Found: /favicon.ico\n",
            "[Kss]: Not Found: /favicon.ico\n",
            "[20/Jun/2024 16:20:09] \u001b[33m\"GET /favicon.ico HTTP/1.1\" 404 2289\u001b[0m\n",
            "싫어요\n",
            ">> 입력하신 내용에서 우울이 느껴집니다.\n",
            "100.0%로 우울합니다.\n",
            "[20/Jun/2024 16:20:29] \u001b[m\"POST / HTTP/1.1\" 200 606\u001b[0m\n",
            "Not Found: /favicon.ico\n",
            "[Kss]: Not Found: /favicon.ico\n",
            "[20/Jun/2024 16:20:29] \u001b[33m\"GET /favicon.ico HTTP/1.1\" 404 2289\u001b[0m\n",
            "/content/diary_project/diary/depression_model.py changed, reloading.\n",
            "[Kss]: /content/diary_project/diary/depression_model.py changed, reloading.\n",
            "Watching for file changes with StatReloader\n",
            "Performing system checks...\n",
            "\n",
            "The tokenizer class you load from this checkpoint is not the same type as the class this function is called from. It may result in unexpected tokenization. \n",
            "The tokenizer class you load from this checkpoint is 'XLNetTokenizer'. \n",
            "The class this function is called from is 'KoBERTTokenizer'.\n",
            "System check identified no issues (0 silenced).\n",
            "\u001b[31m\n",
            "You have 18 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): admin, auth, contenttypes, sessions.\u001b[0m\n",
            "\u001b[31mRun 'python manage.py migrate' to apply them.\u001b[0m\n",
            "June 20, 2024 - 16:23:32\n",
            "Django version 5.0.6, using settings 'diary_project.settings'\n",
            "Starting development server at http://127.0.0.1:8000/\n",
            "Quit the server with CONTROL-C.\n",
            "\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "!python manage.py startapp diary"
      ],
      "metadata": {
        "id": "DQkcrcPWxqRC"
      },
      "execution_count": 15,
      "outputs": []
    },
    {
      "cell_type": "code",
      "source": [
        "!pip install 'git+https://github.com/SKTBrain/KoBERT.git#egg=kobert_tokenizer&subdirectory=kobert_hf'"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "KBemrDIQyW7I",
        "outputId": "6efc68e8-9359-41a6-ddef-68f3046d934d"
      },
      "execution_count": 17,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Collecting kobert_tokenizer\n",
            "  Cloning https://github.com/SKTBrain/KoBERT.git to /tmp/pip-install-rhbr01em/kobert-tokenizer_ae28cb1bc26e43208f969702edd78db8\n",
            "  Running command git clone --filter=blob:none --quiet https://github.com/SKTBrain/KoBERT.git /tmp/pip-install-rhbr01em/kobert-tokenizer_ae28cb1bc26e43208f969702edd78db8\n",
            "  Resolved https://github.com/SKTBrain/KoBERT.git to commit 47a69af87928fc24e20f571fe10c3cc9dd9af9a3\n",
            "  Preparing metadata (setup.py) ... \u001b[?25l\u001b[?25hdone\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "!pip install numpy==1.23.1\n",
        "!pip install kss"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "vxoVOcb60ev0",
        "outputId": "92723b3f-0101-4ae3-a702-1f2079e09bb1"
      },
      "execution_count": 1,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Requirement already satisfied: numpy==1.23.1 in /usr/local/lib/python3.10/dist-packages (1.23.1)\n",
            "Collecting kss\n",
            "  Using cached kss-6.0.4.tar.gz (1.1 MB)\n",
            "  Preparing metadata (setup.py) ... \u001b[?25l\u001b[?25hdone\n",
            "Collecting emoji==1.2.0 (from kss)\n",
            "  Downloading emoji-1.2.0-py3-none-any.whl (131 kB)\n",
            "\u001b[2K     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m131.3/131.3 kB\u001b[0m \u001b[31m1.8 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
            "\u001b[?25hCollecting pecab (from kss)\n",
            "  Downloading pecab-1.0.8.tar.gz (26.4 MB)\n",
            "\u001b[2K     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m26.4/26.4 MB\u001b[0m \u001b[31m10.1 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
            "\u001b[?25h  Preparing metadata (setup.py) ... \u001b[?25l\u001b[?25hdone\n",
            "Requirement already satisfied: networkx in /usr/local/lib/python3.10/dist-packages (from kss) (3.3)\n",
            "Collecting jamo (from kss)\n",
            "  Downloading jamo-0.4.1-py3-none-any.whl (9.5 kB)\n",
            "Collecting hangul-jamo (from kss)\n",
            "  Downloading hangul_jamo-1.0.1-py3-none-any.whl (4.4 kB)\n",
            "Collecting tossi (from kss)\n",
            "  Downloading tossi-0.3.1.tar.gz (11 kB)\n",
            "  Preparing metadata (setup.py) ... \u001b[?25l\u001b[?25hdone\n",
            "Collecting distance (from kss)\n",
            "  Downloading Distance-0.1.3.tar.gz (180 kB)\n",
            "\u001b[2K     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m180.3/180.3 kB\u001b[0m \u001b[31m12.7 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
            "\u001b[?25h  Preparing metadata (setup.py) ... \u001b[?25l\u001b[?25hdone\n",
            "Collecting pyyaml==6.0 (from kss)\n",
            "  Downloading PyYAML-6.0-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (682 kB)\n",
            "\u001b[2K     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m682.2/682.2 kB\u001b[0m \u001b[31m28.4 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
            "\u001b[?25hCollecting unidecode (from kss)\n",
            "  Downloading Unidecode-1.3.8-py3-none-any.whl (235 kB)\n",
            "\u001b[2K     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m235.5/235.5 kB\u001b[0m \u001b[31m15.7 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
            "\u001b[?25hCollecting cmudict (from kss)\n",
            "  Downloading cmudict-1.0.23-py3-none-any.whl (939 kB)\n",
            "\u001b[2K     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m939.4/939.4 kB\u001b[0m \u001b[31m38.8 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
            "\u001b[?25hCollecting koparadigm (from kss)\n",
            "  Downloading koparadigm-0.10.0-py3-none-any.whl (1.6 MB)\n",
            "\u001b[2K     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m1.6/1.6 MB\u001b[0m \u001b[31m43.0 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
            "\u001b[?25hCollecting kollocate (from kss)\n",
            "  Downloading kollocate-0.0.2-py3-none-any.whl (72.2 MB)\n",
            "\u001b[2K     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m72.2/72.2 MB\u001b[0m \u001b[31m6.6 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
            "\u001b[?25hCollecting bs4 (from kss)\n",
            "  Downloading bs4-0.0.2-py2.py3-none-any.whl (1.2 kB)\n",
            "Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (from kss) (1.23.1)\n",
            "Requirement already satisfied: pytest in /usr/local/lib/python3.10/dist-packages (from kss) (7.4.4)\n",
            "Requirement already satisfied: scipy in /usr/local/lib/python3.10/dist-packages (from kss) (1.11.4)\n",
            "Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.10/dist-packages (from bs4->kss) (4.12.3)\n",
            "Requirement already satisfied: importlib-metadata>=5 in /usr/local/lib/python3.10/dist-packages (from cmudict->kss) (7.1.0)\n",
            "Requirement already satisfied: importlib-resources>=5 in /usr/local/lib/python3.10/dist-packages (from cmudict->kss) (6.4.0)\n",
            "Collecting whoosh (from kollocate->kss)\n",
            "  Downloading Whoosh-2.7.4-py2.py3-none-any.whl (468 kB)\n",
            "\u001b[2K     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m468.8/468.8 kB\u001b[0m \u001b[31m28.8 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
            "\u001b[?25hCollecting xlrd==1.2.0 (from koparadigm->kss)\n",
            "  Downloading xlrd-1.2.0-py2.py3-none-any.whl (103 kB)\n",
            "\u001b[2K     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m103.3/103.3 kB\u001b[0m \u001b[31m10.4 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
            "\u001b[?25hRequirement already satisfied: pyarrow in /usr/local/lib/python3.10/dist-packages (from pecab->kss) (14.0.2)\n",
            "Requirement already satisfied: regex in /usr/local/lib/python3.10/dist-packages (from pecab->kss) (2024.5.15)\n",
            "Requirement already satisfied: iniconfig in /usr/local/lib/python3.10/dist-packages (from pytest->kss) (2.0.0)\n",
            "Requirement already satisfied: packaging in /usr/local/lib/python3.10/dist-packages (from pytest->kss) (24.1)\n",
            "Requirement already satisfied: pluggy<2.0,>=0.12 in /usr/local/lib/python3.10/dist-packages (from pytest->kss) (1.5.0)\n",
            "Requirement already satisfied: exceptiongroup>=1.0.0rc8 in /usr/local/lib/python3.10/dist-packages (from pytest->kss) (1.2.1)\n",
            "Requirement already satisfied: tomli>=1.0.0 in /usr/local/lib/python3.10/dist-packages (from pytest->kss) (2.0.1)\n",
            "Requirement already satisfied: bidict in /usr/local/lib/python3.10/dist-packages (from tossi->kss) (0.23.1)\n",
            "Requirement already satisfied: six in /usr/local/lib/python3.10/dist-packages (from tossi->kss) (1.16.0)\n",
            "Requirement already satisfied: zipp>=0.5 in /usr/local/lib/python3.10/dist-packages (from importlib-metadata>=5->cmudict->kss) (3.19.2)\n",
            "Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.10/dist-packages (from beautifulsoup4->bs4->kss) (2.5)\n",
            "Building wheels for collected packages: kss, distance, pecab, tossi\n",
            "  Building wheel for kss (setup.py) ... \u001b[?25l\u001b[?25hdone\n",
            "  Created wheel for kss: filename=kss-6.0.4-cp310-cp310-linux_x86_64.whl size=1446490 sha256=1a9095e3ae8994b4e16531a0d71d527869d72e7a07faa12dfd7930f20b199a77\n",
            "  Stored in directory: /root/.cache/pip/wheels/dd/70/d5/c9308346829b1eb9e7267d74696919d2453aee6ce350f98b3b\n",
            "  Building wheel for distance (setup.py) ... \u001b[?25l\u001b[?25hdone\n",
            "  Created wheel for distance: filename=Distance-0.1.3-py3-none-any.whl size=16258 sha256=2003a5c177fbcfa2a05d2d7b3276c65c044ff1e9a6ee9bc0859d1933a3df359a\n",
            "  Stored in directory: /root/.cache/pip/wheels/e8/bb/de/f71bf63559ea9a921059a5405806f7ff6ed612a9231c4a9309\n",
            "  Building wheel for pecab (setup.py) ... \u001b[?25l\u001b[?25hdone\n",
            "  Created wheel for pecab: filename=pecab-1.0.8-py3-none-any.whl size=26646664 sha256=15d653f89df2bf2dd3bc6f828dacceaa008518063a10d0e7b88455d0463a79f0\n",
            "  Stored in directory: /root/.cache/pip/wheels/5c/6f/b4/ab61b8863d7d8b1409def8ae31adcaa089fa91b8d022ec309d\n",
            "  Building wheel for tossi (setup.py) ... \u001b[?25l\u001b[?25hdone\n",
            "  Created wheel for tossi: filename=tossi-0.3.1-py3-none-any.whl size=12130 sha256=e9f8b5e5f3d7f9a8e495b3b4953d3f22b1808a229f5ac074853a174c4c4e9452\n",
            "  Stored in directory: /root/.cache/pip/wheels/a7/18/60/1094a6fe93c8063efcd3e6700d09328216682e495a3c51af9f\n",
            "Successfully built kss distance pecab tossi\n",
            "Installing collected packages: whoosh, jamo, hangul-jamo, emoji, distance, xlrd, unidecode, tossi, pyyaml, kollocate, pecab, koparadigm, cmudict, bs4, kss\n",
            "  Attempting uninstall: xlrd\n",
            "    Found existing installation: xlrd 2.0.1\n",
            "    Uninstalling xlrd-2.0.1:\n",
            "      Successfully uninstalled xlrd-2.0.1\n",
            "  Attempting uninstall: pyyaml\n",
            "    Found existing installation: PyYAML 6.0.1\n",
            "    Uninstalling PyYAML-6.0.1:\n",
            "      Successfully uninstalled PyYAML-6.0.1\n",
            "Successfully installed bs4-0.0.2 cmudict-1.0.23 distance-0.1.3 emoji-1.2.0 hangul-jamo-1.0.1 jamo-0.4.1 kollocate-0.0.2 koparadigm-0.10.0 kss-6.0.4 pecab-1.0.8 pyyaml-6.0 tossi-0.3.1 unidecode-1.3.8 whoosh-2.7.4 xlrd-1.2.0\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "!pip install mxnet\n",
        "!pip install gluonnlp pandas tqdm\n",
        "!pip install sentencepiece\n",
        "!pip install transformers\n",
        "!pip install torch"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "IUgHc7Jk0iuJ",
        "outputId": "f793542c-388f-42b3-b53b-8d0f2bd8a5fb"
      },
      "execution_count": 2,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Collecting mxnet\n",
            "  Downloading mxnet-1.9.1-py3-none-manylinux2014_x86_64.whl (49.1 MB)\n",
            "\u001b[2K     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m49.1/49.1 MB\u001b[0m \u001b[31m10.1 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
            "\u001b[?25hRequirement already satisfied: numpy<2.0.0,>1.16.0 in /usr/local/lib/python3.10/dist-packages (from mxnet) (1.23.1)\n",
            "Requirement already satisfied: requests<3,>=2.20.0 in /usr/local/lib/python3.10/dist-packages (from mxnet) (2.31.0)\n",
            "Collecting graphviz<0.9.0,>=0.8.1 (from mxnet)\n",
            "  Downloading graphviz-0.8.4-py2.py3-none-any.whl (16 kB)\n",
            "Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2.20.0->mxnet) (3.3.2)\n",
            "Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2.20.0->mxnet) (3.7)\n",
            "Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2.20.0->mxnet) (2.0.7)\n",
            "Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2.20.0->mxnet) (2024.6.2)\n",
            "Installing collected packages: graphviz, mxnet\n",
            "  Attempting uninstall: graphviz\n",
            "    Found existing installation: graphviz 0.20.3\n",
            "    Uninstalling graphviz-0.20.3:\n",
            "      Successfully uninstalled graphviz-0.20.3\n",
            "Successfully installed graphviz-0.8.4 mxnet-1.9.1\n",
            "Collecting gluonnlp\n",
            "  Downloading gluonnlp-0.10.0.tar.gz (344 kB)\n",
            "\u001b[2K     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m344.5/344.5 kB\u001b[0m \u001b[31m6.6 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
            "\u001b[?25h  Preparing metadata (setup.py) ... \u001b[?25l\u001b[?25hdone\n",
            "Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (2.0.3)\n",
            "Requirement already satisfied: tqdm in /usr/local/lib/python3.10/dist-packages (4.66.4)\n",
            "Requirement already satisfied: numpy>=1.16.0 in /usr/local/lib/python3.10/dist-packages (from gluonnlp) (1.23.1)\n",
            "Requirement already satisfied: cython in /usr/local/lib/python3.10/dist-packages (from gluonnlp) (3.0.10)\n",
            "Requirement already satisfied: packaging in /usr/local/lib/python3.10/dist-packages (from gluonnlp) (24.1)\n",
            "Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas) (2.8.2)\n",
            "Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2023.4)\n",
            "Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2024.1)\n",
            "Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)\n",
            "Building wheels for collected packages: gluonnlp\n",
            "  Building wheel for gluonnlp (setup.py) ... \u001b[?25l\u001b[?25hdone\n",
            "  Created wheel for gluonnlp: filename=gluonnlp-0.10.0-cp310-cp310-linux_x86_64.whl size=661750 sha256=f482a742b1161b7b54bf811893245e0912a124800a9aa72be063b6afd46fa9e9\n",
            "  Stored in directory: /root/.cache/pip/wheels/1a/1e/0d/99f55911d90f2b95b9f7c176d5813ef3622894a4b30fde6bd3\n",
            "Successfully built gluonnlp\n",
            "Installing collected packages: gluonnlp\n",
            "Successfully installed gluonnlp-0.10.0\n",
            "Requirement already satisfied: sentencepiece in /usr/local/lib/python3.10/dist-packages (0.1.99)\n",
            "Requirement already satisfied: transformers in /usr/local/lib/python3.10/dist-packages (4.41.2)\n",
            "Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from transformers) (3.14.0)\n",
            "Requirement already satisfied: huggingface-hub<1.0,>=0.23.0 in /usr/local/lib/python3.10/dist-packages (from transformers) (0.23.3)\n",
            "Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.10/dist-packages (from transformers) (1.23.1)\n",
            "Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from transformers) (24.1)\n",
            "Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.10/dist-packages (from transformers) (6.0)\n",
            "Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.10/dist-packages (from transformers) (2024.5.15)\n",
            "Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from transformers) (2.31.0)\n",
            "Requirement already satisfied: tokenizers<0.20,>=0.19 in /usr/local/lib/python3.10/dist-packages (from transformers) (0.19.1)\n",
            "Requirement already satisfied: safetensors>=0.4.1 in /usr/local/lib/python3.10/dist-packages (from transformers) (0.4.3)\n",
            "Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.10/dist-packages (from transformers) (4.66.4)\n",
            "Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub<1.0,>=0.23.0->transformers) (2023.6.0)\n",
            "Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub<1.0,>=0.23.0->transformers) (4.12.2)\n",
            "Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests->transformers) (3.3.2)\n",
            "Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->transformers) (3.7)\n",
            "Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests->transformers) (2.0.7)\n",
            "Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests->transformers) (2024.6.2)\n",
            "Requirement already satisfied: torch in /usr/local/lib/python3.10/dist-packages (2.3.0+cu121)\n",
            "Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from torch) (3.14.0)\n",
            "Requirement already satisfied: typing-extensions>=4.8.0 in /usr/local/lib/python3.10/dist-packages (from torch) (4.12.2)\n",
            "Requirement already satisfied: sympy in /usr/local/lib/python3.10/dist-packages (from torch) (1.12.1)\n",
            "Requirement already satisfied: networkx in /usr/local/lib/python3.10/dist-packages (from torch) (3.3)\n",
            "Requirement already satisfied: jinja2 in /usr/local/lib/python3.10/dist-packages (from torch) (3.1.4)\n",
            "Requirement already satisfied: fsspec in /usr/local/lib/python3.10/dist-packages (from torch) (2023.6.0)\n",
            "Collecting nvidia-cuda-nvrtc-cu12==12.1.105 (from torch)\n",
            "  Using cached nvidia_cuda_nvrtc_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (23.7 MB)\n",
            "Collecting nvidia-cuda-runtime-cu12==12.1.105 (from torch)\n",
            "  Using cached nvidia_cuda_runtime_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (823 kB)\n",
            "Collecting nvidia-cuda-cupti-cu12==12.1.105 (from torch)\n",
            "  Using cached nvidia_cuda_cupti_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (14.1 MB)\n",
            "Collecting nvidia-cudnn-cu12==8.9.2.26 (from torch)\n",
            "  Using cached nvidia_cudnn_cu12-8.9.2.26-py3-none-manylinux1_x86_64.whl (731.7 MB)\n",
            "Collecting nvidia-cublas-cu12==12.1.3.1 (from torch)\n",
            "  Using cached nvidia_cublas_cu12-12.1.3.1-py3-none-manylinux1_x86_64.whl (410.6 MB)\n",
            "Collecting nvidia-cufft-cu12==11.0.2.54 (from torch)\n",
            "  Using cached nvidia_cufft_cu12-11.0.2.54-py3-none-manylinux1_x86_64.whl (121.6 MB)\n",
            "Collecting nvidia-curand-cu12==10.3.2.106 (from torch)\n",
            "  Using cached nvidia_curand_cu12-10.3.2.106-py3-none-manylinux1_x86_64.whl (56.5 MB)\n",
            "Collecting nvidia-cusolver-cu12==11.4.5.107 (from torch)\n",
            "  Using cached nvidia_cusolver_cu12-11.4.5.107-py3-none-manylinux1_x86_64.whl (124.2 MB)\n",
            "Collecting nvidia-cusparse-cu12==12.1.0.106 (from torch)\n",
            "  Using cached nvidia_cusparse_cu12-12.1.0.106-py3-none-manylinux1_x86_64.whl (196.0 MB)\n",
            "Collecting nvidia-nccl-cu12==2.20.5 (from torch)\n",
            "  Using cached nvidia_nccl_cu12-2.20.5-py3-none-manylinux2014_x86_64.whl (176.2 MB)\n",
            "Collecting nvidia-nvtx-cu12==12.1.105 (from torch)\n",
            "  Using cached nvidia_nvtx_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (99 kB)\n",
            "Requirement already satisfied: triton==2.3.0 in /usr/local/lib/python3.10/dist-packages (from torch) (2.3.0)\n",
            "Collecting nvidia-nvjitlink-cu12 (from nvidia-cusolver-cu12==11.4.5.107->torch)\n",
            "  Downloading nvidia_nvjitlink_cu12-12.5.40-py3-none-manylinux2014_x86_64.whl (21.3 MB)\n",
            "\u001b[2K     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m21.3/21.3 MB\u001b[0m \u001b[31m46.5 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
            "\u001b[?25hRequirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from jinja2->torch) (2.1.5)\n",
            "Requirement already satisfied: mpmath<1.4.0,>=1.1.0 in /usr/local/lib/python3.10/dist-packages (from sympy->torch) (1.3.0)\n",
            "Installing collected packages: nvidia-nvtx-cu12, nvidia-nvjitlink-cu12, nvidia-nccl-cu12, nvidia-curand-cu12, nvidia-cufft-cu12, nvidia-cuda-runtime-cu12, nvidia-cuda-nvrtc-cu12, nvidia-cuda-cupti-cu12, nvidia-cublas-cu12, nvidia-cusparse-cu12, nvidia-cudnn-cu12, nvidia-cusolver-cu12\n",
            "Successfully installed nvidia-cublas-cu12-12.1.3.1 nvidia-cuda-cupti-cu12-12.1.105 nvidia-cuda-nvrtc-cu12-12.1.105 nvidia-cuda-runtime-cu12-12.1.105 nvidia-cudnn-cu12-8.9.2.26 nvidia-cufft-cu12-11.0.2.54 nvidia-curand-cu12-10.3.2.106 nvidia-cusolver-cu12-11.4.5.107 nvidia-cusparse-cu12-12.1.0.106 nvidia-nccl-cu12-2.20.5 nvidia-nvjitlink-cu12-12.5.40 nvidia-nvtx-cu12-12.1.105\n"
          ]
        }
      ]
    }
  ]
}